import XCTest
import AppKit
@testable import MirrorKit
@testable import MirrorKitUI

/// Guards over the accent ramps lifted out of the guest's `Apple platinum`
/// theme file (PlatinumAccentRamps.swift, generated by
/// tools/extract-assets-offline).
///
/// These are not taste. Each one fails on a specific way the extraction
/// could be wrong — a mis-taken `clut` layout, a channel conversion that
/// drops precision, the empty ramp read as a missing one, or a renderer
/// constant quietly drifting away from the number the machine gave.
final class AccentRampTests: XCTestCase {

    func testTwentyOneRampsWithTheNamesTheThemeFileCarries() {
        XCTAssertEqual(PlatinumAccent.all.count, 21)
        // The names are the Appearance control panel's own list. A rename
        // here means the extraction read a different resource.
        XCTAssertEqual(PlatinumAccent.named("Lavender")?.clutID, 208)
        XCTAssertEqual(PlatinumAccent.named("Black & White")?.clutID, 220)
        XCTAssertNil(PlatinumAccent.named("Purple"),
                     "Purple is a HIGHLIGHT colour name, not a ramp — the "
                     + "two lists are different and must not be merged")
    }

    func testEveryRampHasEightStepsExceptTheEmptyOne() {
        for ramp in PlatinumAccent.all where ramp.name != "Black & White" {
            XCTAssertEqual(ramp.steps.count, 8, "\(ramp.name)")
        }
        // Not an extraction failure: `Black & White` really is an 8-byte
        // clut with ctSize -1. Reading it as missing would be the bug.
        let bw = PlatinumAccent.named("Black & White")
        XCTAssertEqual(bw?.steps, [])
        XCTAssertEqual(bw?.isEmpty, true)
    }

    func testRampsRunLightToDarkAndEndInBlack() {
        func luma(_ c: UInt32) -> Int {
            let r = Int((c >> 16) & 0xFF), g = Int((c >> 8) & 0xFF)
            return 2 * r + 3 * g + Int(c & 0xFF)
        }
        for ramp in PlatinumAccent.all where !ramp.isEmpty {
            XCTAssertEqual(ramp.steps.last, 0x000000,
                           "\(ramp.name) does not end in black")
            // Monotone darkening is the shape of an accent ramp; a table
            // read at the wrong stride would scramble it.
            for i in 1..<ramp.steps.count {
                XCTAssertLessThanOrEqual(luma(ramp.steps[i]),
                                         luma(ramp.steps[i - 1]),
                                         "\(ramp.name) step \(i) is lighter "
                                         + "than the one before it")
            }
            for step in ramp.steps {
                XCTAssertEqual(step & 0xFF00_0000, 0,
                               "\(ramp.name) has bits above 24 — a channel "
                               + "conversion overflowed")
            }
        }
    }

    func testActiveRampIsTheOneTheDefaultSceneNames() {
        XCTAssertEqual(PlatinumAccent.active.name, "Lavender")
        XCTAssertEqual(PlatinumAccent.active.clutID, 208)
        // The default scene writes its highlight as a literal RGBColor in a
        // slot separate from the accent name. That it equals the ramp's
        // second step is the corroboration the extraction rests on: two
        // independently-written fields agreeing.
        XCTAssertEqual(PlatinumAccent.activeHighlight, 0xCCCCFF)
        XCTAssertEqual(PlatinumAccent.active.steps[1],
                       PlatinumAccent.activeHighlight)
    }

    /// The difference list, as a test rather than as prose.
    ///
    /// `selection` was ported as 0x333399 from a CSS file and the theme file
    /// agrees exactly — that is a finding, and this is where it stops being
    /// a claim. `highlight` is where the port was wrong: it borrowed the
    /// chrome grey 0xCCCCCC, which is the *Gray Space* theme's highlight,
    /// not this machine's.
    func testTheRendererDrawsTheMeasuredNumbers() {
        XCTAssertEqual(PlatinumAccent.active.steps[4], 0x333399,
                       "the ported selection constant is Lavender's fifth "
                       + "step; if this moves, the port and the measurement "
                       + "have stopped agreeing and the difference list in "
                       + "docs/asset-extraction-offline.md is stale")
        XCTAssertNotEqual(PlatinumAccent.activeHighlight, 0xCCCCCC,
                          "0xCCCCCC is Platinum.g2 and the Gray Space "
                          + "theme's highlight — the value this replaced")
    }
}

/// The wiring, proved at the pixels.
///
/// It needs its own scene because NONE of the nine captures in
/// NOWMirrorContentCoverageTests has a selected list row — regenerating them
/// with the highlight forced to magenta changed nothing at all. So the
/// existing corpus cannot say whether this constant reaches the screen, and
/// a change nobody can see is a change nobody has verified.
@MainActor
final class AccentHighlightRenderTests: XCTestCase {

    static func oneSelectedRow() -> Scene {
        let r = Rect(l: 100, t: 100, r: 500, b: 400)
        var w = Scene.Window(id: "1.0/List#0", app: "Finder", psn: "1.0",
                             title: "List", kind: 0, rect: r, front: true,
                             z: 0, visible: true, controls: [], text: nil,
                             items: nil, display: nil)
        w.controls = [.init(
            ref: "list", role: "control", title: "",
            rect: Rect(l: 20, t: 40, r: 380, b: 240),
            enabled: true, visible: true,
            semantic: .init(knowledge: .known, kind: "listBox",
                            listCells: [
                                .init(row: 0, column: 0, text: "Macintosh HD",
                                      selected: true),
                                .init(row: 1, column: 0, text: "Documents",
                                      selected: false),
                            ],
                            provenance: "guest",
                            completeness: .complete))]
        let scene = Scene(version: 0, seq: 1, source: "mock", capturedAt: 0,
                          screen: .init(w: 800, h: 600), apps: [],
                          processes: nil, menubar: nil, windows: [w],
                          desktopItems: nil, meta: .init(errors: []))
        return scene
    }

    func testASelectedListRowIsFilledWithTheMeasuredHighlight() throws {
        let scene = Self.oneSelectedRow()
        try assertSomePixel(of: scene, is: Platinum.highlightFallbackRGB,
                            "no pixel of the selected row carries the "
                            + "fallback highlight - it never reached the "
                            + "canvas")
    }

    /// **And a guest that names its own highlight beats the fallback.**
    ///
    /// This is the assertion the old version of this file could not make,
    /// because there was nowhere for the guest to say. The constant it
    /// pinned - 0xCCCCFF, out of the theme FILE - turned out never to have
    /// been on a screen: the live machine answers 0x97A1DE and its own
    /// screendump agrees. A renderer keyed to a constant is wrong in
    /// exactly that way, silently, so what is pinned here is that the WIRE
    /// wins.
    func testADeclaredHighlightBeatsTheFallback() throws {
        var scene = Self.oneSelectedRow()
        scene.meta.theme = .init(highlight: "#FF00FF", depth: 32)
        try assertSomePixel(of: scene, is: 0xFF00FF,
                            "the guest named its highlight and no pixel "
                            + "carries it")
        try assertNoPixel(of: scene, is: Platinum.highlightFallbackRGB,
                          "the fallback still reached the canvas over a "
                          + "colour the guest had named")
    }

    private func assertSomePixel(of scene: Scene, is rgb: UInt32,
                                 _ message: String) throws {
        XCTAssertTrue(try pixelPresent(scene, rgb), message)
    }

    private func assertNoPixel(of scene: Scene, is rgb: UInt32,
                               _ message: String) throws {
        XCTAssertFalse(try pixelPresent(scene, rgb), message)
    }

    private func pixelPresent(_ scene: Scene, _ rgb: UInt32) throws -> Bool {
        let png = try RenderShot.png(scene: scene)
        let rep = try XCTUnwrap(NSBitmapImageRep(data: png))
        let want = (Int((rgb >> 16) & 0xFF), Int((rgb >> 8) & 0xFF),
                    Int(rgb & 0xFF))
        for y in 0..<rep.pixelsHigh {
            for x in 0..<rep.pixelsWide {
                guard let c = rep.colorAt(x: x, y: y) else { continue }
                let px = (Int((c.redComponent * 255).rounded()),
                          Int((c.greenComponent * 255).rounded()),
                          Int((c.blueComponent * 255).rounded()))
                if px == want { return true }
            }
        }
        return false
    }
}
