# buildstamp.cmake — derive the agent's build identity from its SOURCES.
#
# Run as `cmake -DSRC_DIR=... -DOUT=... -P cmake/buildstamp.cmake` by a custom
# target that runs on EVERY build (see CMakeLists.txt).
#
# Why this exists: `kBuildStamp` used to be `__DATE__ " " __TIME__` inside
# mirrorverbs.c, so a build whose only change was main.c recompiled main.c,
# relinked, and shipped a binary reporting the OLD stamp. A deploy could not be
# confirmed, and a lane that deployed and then measured the previous binary
# would report a confident, false number. Measured 2026-07-31: touching main.c
# alone left the reported stamp unchanged.
#
# The fix is content, not clock: hash every source the application is built
# from, in a stable order, and make the hash the identity. It cannot go stale,
# because it is a function of exactly the bytes that produced the binary — and
# an unchanged source tree deliberately reproduces the same stamp, which is the
# other half of the question ("is this the same build?").
#
# The header is rewritten only when its contents change, so an unchanged tree
# does not force a recompile of everything that includes it.

file(GLOB _stamp_sources
     "${SRC_DIR}/*.c"
     "${SRC_DIR}/*.h"
     "${SRC_DIR}/*.r")
list(SORT _stamp_sources)                 # order must not depend on the FS

set(_stamp_accum "")
foreach(_f IN LISTS _stamp_sources)
    file(SHA1 "${_f}" _h)
    get_filename_component(_n "${_f}" NAME)
    string(APPEND _stamp_accum "${_n} ${_h}\n")
endforeach()
string(SHA1 _stamp_hash "${_stamp_accum}")
string(SUBSTRING "${_stamp_hash}" 0 12 _stamp_short)

# The clock is carried too, but only as context beside the hash: it answers
# "when was this built", never "which bytes are these".
string(TIMESTAMP _stamp_when "%Y-%m-%dT%H:%M:%S" UTC)

set(_stamp_body
"/* GENERATED by cmake/buildstamp.cmake — do not edit, do not commit. */
#ifndef MIRROR_BUILDSTAMP_H
#define MIRROR_BUILDSTAMP_H

/* SHA-1 over every src/*.{c,h,r}, name-sorted, 12 hex chars. Changing ANY
 * source moves it; changing none reproduces it. */
#define MIRROR_SRC_HASH \"${_stamp_short}\"
#define MIRROR_BUILT_AT \"${_stamp_when}Z\"

#endif /* MIRROR_BUILDSTAMP_H */
")

set(_stamp_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _stamp_old)
endif()
if(NOT _stamp_old STREQUAL _stamp_body)
    file(WRITE "${OUT}" "${_stamp_body}")
    message(STATUS "build stamp: ${_stamp_short} (${_stamp_when}Z)")
endif()
