/*
 * census_selectors.h - the documented Gestalt selector table the census
 * walks. Snapshotted mechanically from Universal Interfaces 3.4 Gestalt.h
 * (Technology: Mac OS 9.1), the same header this application compiles
 * against - each entry references the Apple symbol, so a selector that
 * leaves the interfaces fails the build instead of drifting. Labels are
 * the Apple symbol names minus the gestalt prefix (machine_names.h sets
 * the precedent: snapshot reference data, cite the authority).
 *
 * Gestalt has no enumeration API: this table IS the walk, and the census
 * report says so. A selector that does not answer is skipped, exactly as
 * the machine answered.
 */
#ifndef NOW_CENSUS_SELECTORS_H
#define NOW_CENSUS_SELECTORS_H

#include <Carbon.h>

/* How to render a selector's response; raw always survives beside it. */
enum {
    kCensusSelNum = 0,      /* plain number (fourcc-looking values shown as such) */
    kCensusSelAttr,         /* bit mask; known bits named, unknown set bits called out */
    kCensusSelVersion,      /* BCD-style version when it decodes as one */
    kCensusSelSize,         /* bytes */
    kCensusSelCount,        /* a count */
    kCensusSelAddr          /* an address; shown in hex */
};

typedef struct {
    unsigned long selector;
    const char *name;       /* Apple symbol minus the gestalt prefix */
    short kind;
} NowCensusSelector;

static const NowCensusSelector kNowCensusSelectors[] = {
    { gestaltAddressingModeAttr, "AddressingModeAttr", kCensusSelAttr },
    { gestaltAFPClient, "AFPClient", kCensusSelNum },
    { gestaltAliasMgrAttr, "AliasMgrAttr", kCensusSelAttr },
    { gestaltAppearanceAttr, "AppearanceAttr", kCensusSelAttr },
    { gestaltAppearanceVersion, "AppearanceVersion", kCensusSelVersion },
    { gestaltArbitorAttr, "ArbitorAttr", kCensusSelAttr },
    { gestaltAppleScriptVersion, "AppleScriptVersion", kCensusSelVersion },
    { gestaltAppleScriptAttr, "AppleScriptAttr", kCensusSelAttr },
    { gestaltATAAttr, "ATAAttr", kCensusSelAttr },
    { gestaltATalkVersion, "ATalkVersion", kCensusSelVersion },
    { gestaltAppleTalkVersion, "AppleTalkVersion", kCensusSelVersion },
    { gestaltAUXVersion, "AUXVersion", kCensusSelVersion },
    { gestaltMacOSCompatibilityBoxAttr, "MacOSCompatibilityBoxAttr", kCensusSelAttr },
    { gestaltBusClkSpeed, "BusClkSpeed", kCensusSelNum },
    { gestaltCloseViewAttr, "CloseViewAttr", kCensusSelAttr },
    { gestaltCarbonVersion, "CarbonVersion", kCensusSelVersion },
    { gestaltCFMAttr, "CFMAttr", kCensusSelAttr },
    { gestaltCollectionMgrVersion, "CollectionMgrVersion", kCensusSelVersion },
    { gestaltColorMatchingAttr, "ColorMatchingAttr", kCensusSelAttr },
    { gestaltColorMatchingVersion, "ColorMatchingVersion", kCensusSelVersion },
    { gestaltControlMgrVersion, "ControlMgrVersion", kCensusSelVersion },
    { gestaltControlMgrAttr, "ControlMgrAttr", kCensusSelAttr },
    { gestaltConnMgrAttr, "ConnMgrAttr", kCensusSelAttr },
    { gestaltColorPickerVersion, "ColorPickerVersion", kCensusSelVersion },
    { gestaltComponentMgr, "ComponentMgr", kCensusSelNum },
    { gestaltComponentPlatform, "ComponentPlatform", kCensusSelNum },
    { gestaltNativeCPUtype, "NativeCPUtype", kCensusSelNum },
    { gestaltNativeCPUfamily, "NativeCPUfamily", kCensusSelNum },
    { gestaltCRMAttr, "CRMAttr", kCensusSelAttr },
    { gestaltControlStripVersion, "ControlStripVersion", kCensusSelVersion },
    { gestaltCTBVersion, "CTBVersion", kCensusSelVersion },
    { gestaltDBAccessMgrAttr, "DBAccessMgrAttr", kCensusSelAttr },
    { gestaltDiskCacheSize, "DiskCacheSize", kCensusSelSize },
    { gestaltSDPFindVersion, "SDPFindVersion", kCensusSelVersion },
    { gestaltDictionaryMgrAttr, "DictionaryMgrAttr", kCensusSelAttr },
    { gestaltDITLExtAttr, "DITLExtAttr", kCensusSelAttr },
    { gestaltDialogMgrAttr, "DialogMgrAttr", kCensusSelAttr },
    { gestaltDesktopPicturesAttr, "DesktopPicturesAttr", kCensusSelAttr },
    { gestaltDisplayMgrVers, "DisplayMgrVers", kCensusSelNum },
    { gestaltDisplayMgrAttr, "DisplayMgrAttr", kCensusSelAttr },
    { gestaltDragMgrAttr, "DragMgrAttr", kCensusSelAttr },
    { gestaltDrawSprocketVersion, "DrawSprocketVersion", kCensusSelVersion },
    { gestaltDigitalSignatureVersion, "DigitalSignatureVersion", kCensusSelVersion },
    { gestaltDTPFeatures, "DTPFeatures", kCensusSelNum },
    { gestaltDTPInfo, "DTPInfo", kCensusSelNum },
    { gestaltEasyAccessAttr, "EasyAccessAttr", kCensusSelAttr },
    { gestaltEditionMgrAttr, "EditionMgrAttr", kCensusSelAttr },
    { gestaltAppleEventsAttr, "AppleEventsAttr", kCensusSelAttr },
    { gestaltExtensionTableVersion, "ExtensionTableVersion", kCensusSelVersion },
    { gestaltFBCIndexingState, "FBCIndexingState", kCensusSelNum },
    { gestaltFBCVersion, "FBCVersion", kCensusSelVersion },
    { gestaltFileMappingAttr, "FileMappingAttr", kCensusSelAttr },
    { gestaltFloppyAttr, "FloppyAttr", kCensusSelAttr },
    { gestaltFinderAttr, "FinderAttr", kCensusSelAttr },
    { gestaltFindFolderAttr, "FindFolderAttr", kCensusSelAttr },
    { gestaltFindFolderRedirectionAttr, "FindFolderRedirectionAttr", kCensusSelAttr },
    { gestaltFontMgrAttr, "FontMgrAttr", kCensusSelAttr },
    { gestaltFPUType, "FPUType", kCensusSelNum },
    { gestaltFSAttr, "FSAttr", kCensusSelAttr },
    { gestaltAdminFeaturesFlagsAttr, "AdminFeaturesFlagsAttr", kCensusSelAttr },
    { gestaltFSMVersion, "FSMVersion", kCensusSelVersion },
    { gestaltFXfrMgrAttr, "FXfrMgrAttr", kCensusSelAttr },
    { gestaltGraphicsAttr, "GraphicsAttr", kCensusSelAttr },
    { gestaltGraphicsVersion, "GraphicsVersion", kCensusSelVersion },
    { gestaltHardwareAttr, "HardwareAttr", kCensusSelAttr },
    { gestaltHelpMgrAttr, "HelpMgrAttr", kCensusSelAttr },
    { gestaltHardwareVendorCode, "HardwareVendorCode", kCensusSelNum },
    { gestaltCompressionMgr, "CompressionMgr", kCensusSelNum },
    { gestaltIconUtilitiesAttr, "IconUtilitiesAttr", kCensusSelAttr },
    { gestaltInternalDisplay, "InternalDisplay", kCensusSelNum },
    { gestaltKeyboardType, "KeyboardType", kCensusSelNum },
    { gestaltUDFSupport, "UDFSupport", kCensusSelNum },
    { gestaltLowMemorySize, "LowMemorySize", kCensusSelSize },
    { gestaltLogicalRAMSize, "LogicalRAMSize", kCensusSelSize },
    { gestaltMachineType, "MachineType", kCensusSelNum },
    { gestaltSMPMailerVersion, "SMPMailerVersion", kCensusSelVersion },
    { gestaltMediaBay, "MediaBay", kCensusSelNum },
    { gestaltMessageMgrVersion, "MessageMgrVersion", kCensusSelVersion },
    { gestaltMenuMgrAttr, "MenuMgrAttr", kCensusSelAttr },
    { gestaltMultipleUsersState, "MultipleUsersState", kCensusSelNum },
    { gestaltMachineIcon, "MachineIcon", kCensusSelNum },
    { gestaltMiscAttr, "MiscAttr", kCensusSelAttr },
    { gestaltMixedModeVersion, "MixedModeVersion", kCensusSelVersion },
    { gestaltQuickTimeConferencing, "QuickTimeConferencing", kCensusSelNum },
    { gestaltMemoryMapAttr, "MemoryMapAttr", kCensusSelAttr },
    { gestaltMMUType, "MMUType", kCensusSelNum },
    { gestaltUserVisibleMachineName, "UserVisibleMachineName", kCensusSelNum },
    { gestaltMPCallableAPIsAttr, "MPCallableAPIsAttr", kCensusSelAttr },
    { gestaltStdNBPAttr, "StdNBPAttr", kCensusSelAttr },
    { gestaltNotificationMgrAttr, "NotificationMgrAttr", kCensusSelAttr },
    { gestaltNameRegistryVersion, "NameRegistryVersion", kCensusSelVersion },
    { gestaltNuBusSlotCount, "NuBusSlotCount", kCensusSelCount },
    { gestaltOCEToolboxVersion, "OCEToolboxVersion", kCensusSelVersion },
    { gestaltOCEToolboxAttr, "OCEToolboxAttr", kCensusSelAttr },
    { gestaltOpenFirmwareInfo, "OpenFirmwareInfo", kCensusSelNum },
    { gestaltOSAttr, "OSAttr", kCensusSelAttr },
    { gestaltOSTable, "OSTable", kCensusSelAddr },
    { gestaltOpenTptNetworkSetup, "OpenTptNetworkSetup", kCensusSelNum },
    { gestaltOpenTptNetworkSetupVersion, "OpenTptNetworkSetupVersion", kCensusSelVersion },
    { gestaltOpenTptRemoteAccess, "OpenTptRemoteAccess", kCensusSelNum },
    { gestaltOpenTptRemoteAccessVersion, "OpenTptRemoteAccessVersion", kCensusSelVersion },
    { gestaltOpenTptVersions, "OpenTptVersions", kCensusSelVersion },
    { gestaltOpenTpt, "OpenTpt", kCensusSelNum },
    { gestaltPCCard, "PCCard", kCensusSelNum },
    { gestaltProcClkSpeed, "ProcClkSpeed", kCensusSelNum },
    { gestaltPCXAttr, "PCXAttr", kCensusSelAttr },
    { gestaltLogicalPageSize, "LogicalPageSize", kCensusSelSize },
    { gestaltScreenCaptureMain, "ScreenCaptureMain", kCensusSelNum },
    { gestaltScreenCaptureDir, "ScreenCaptureDir", kCensusSelNum },
    { gestaltGXPrintingMgrVersion, "GXPrintingMgrVersion", kCensusSelVersion },
    { gestaltPopupAttr, "PopupAttr", kCensusSelAttr },
    { gestaltPowerMgrAttr, "PowerMgrAttr", kCensusSelAttr },
    { gestaltPowerMgrVers, "PowerMgrVers", kCensusSelNum },
    { gestaltPPCToolboxAttr, "PPCToolboxAttr", kCensusSelAttr },
    { gestaltPowerPCProcessorFeatures, "PowerPCProcessorFeatures", kCensusSelNum },
    { gestaltProcessorType, "ProcessorType", kCensusSelNum },
    { gestaltSDPPromptVersion, "SDPPromptVersion", kCensusSelVersion },
    { gestaltParityAttr, "ParityAttr", kCensusSelAttr },
    { gestaltQD3DVersion, "QD3DVersion", kCensusSelVersion },
    { gestaltQD3DViewer, "QD3DViewer", kCensusSelNum },
    { gestaltQuickdrawVersion, "QuickdrawVersion", kCensusSelVersion },
    { gestaltQD3D, "QD3D", kCensusSelNum },
    { gestaltGXVersion, "GXVersion", kCensusSelVersion },
    { gestaltQuickdrawFeatures, "QuickdrawFeatures", kCensusSelNum },
    { gestaltQDTextVersion, "QDTextVersion", kCensusSelVersion },
    { gestaltQDTextFeatures, "QDTextFeatures", kCensusSelNum },
    { gestaltQuickTimeConferencingInfo, "QuickTimeConferencingInfo", kCensusSelNum },
    { gestaltQuickTimeVersion, "QuickTimeVersion", kCensusSelVersion },
    { gestaltQuickTimeFeatures, "QuickTimeFeatures", kCensusSelNum },
    { gestaltQuickTimeStreamingFeatures, "QuickTimeStreamingFeatures", kCensusSelNum },
    { gestaltQuickTimeStreamingVersion, "QuickTimeStreamingVersion", kCensusSelVersion },
    { gestaltQTVRMgrAttr, "QTVRMgrAttr", kCensusSelAttr },
    { gestaltQTVRMgrVers, "QTVRMgrVers", kCensusSelNum },
    { gestaltPhysicalRAMSize, "PhysicalRAMSize", kCensusSelSize },
    { gestaltRBVAddr, "RBVAddr", kCensusSelNum },
    { gestaltROMSize, "ROMSize", kCensusSelSize },
    { gestaltROMVersion, "ROMVersion", kCensusSelVersion },
    { gestaltResourceMgrAttr, "ResourceMgrAttr", kCensusSelAttr },
    { gestaltResourceMgrBugFixesAttrs, "ResourceMgrBugFixesAttrs", kCensusSelNum },
    { gestaltRealtimeMgrAttr, "RealtimeMgrAttr", kCensusSelAttr },
    { gestaltSafeOFAttr, "SafeOFAttr", kCensusSelAttr },
    { gestaltSCCReadAddr, "SCCReadAddr", kCensusSelNum },
    { gestaltSCCWriteAddr, "SCCWriteAddr", kCensusSelNum },
    { gestaltScrapMgrAttr, "ScrapMgrAttr", kCensusSelAttr },
    { gestaltScriptMgrVersion, "ScriptMgrVersion", kCensusSelVersion },
    { gestaltScriptCount, "ScriptCount", kCensusSelCount },
    { gestaltSCSI, "SCSI", kCensusSelNum },
    { gestaltControlStripAttr, "ControlStripAttr", kCensusSelAttr },
    { gestaltSDPStandardDirectoryVersion, "SDPStandardDirectoryVersion", kCensusSelVersion },
    { gestaltSerialAttr, "SerialAttr", kCensusSelAttr },
    { gestaltShutdownAttributes, "ShutdownAttributes", kCensusSelNum },
    { gestaltNuBusConnectors, "NuBusConnectors", kCensusSelNum },
    { gestaltSlotAttr, "SlotAttr", kCensusSelAttr },
    { gestaltFirstSlotNumber, "FirstSlotNumber", kCensusSelNum },
    { gestaltSoundAttr, "SoundAttr", kCensusSelAttr },
    { gestaltSplitOSAttr, "SplitOSAttr", kCensusSelAttr },
    { gestaltSMPSPSendLetterVersion, "SMPSPSendLetterVersion", kCensusSelVersion },
    { gestaltSpeechRecognitionAttr, "SpeechRecognitionAttr", kCensusSelAttr },
    { gestaltSpeechRecognitionVersion, "SpeechRecognitionVersion", kCensusSelVersion },
    { gestaltSoftwareVendorCode, "SoftwareVendorCode", kCensusSelNum },
    { gestaltSoftwareVendorLicensee, "SoftwareVendorLicensee", kCensusSelNum },
    { gestaltStandardFileAttr, "StandardFileAttr", kCensusSelAttr },
    { gestaltSysArchitecture, "SysArchitecture", kCensusSelNum },
    { gestaltSystemUpdateVersion, "SystemUpdateVersion", kCensusSelVersion },
    { gestaltSystemVersion, "SystemVersion", kCensusSelVersion },
    { gestaltToolboxTable, "ToolboxTable", kCensusSelAddr },
    { gestaltTextEditVersion, "TextEditVersion", kCensusSelVersion },
    { gestaltTEAttr, "TEAttr", kCensusSelAttr },
    { gestaltTeleMgrAttr, "TeleMgrAttr", kCensusSelAttr },
    { gestaltTermMgrAttr, "TermMgrAttr", kCensusSelAttr },
    { gestaltThreadMgrAttr, "ThreadMgrAttr", kCensusSelAttr },
    { gestaltTimeMgrVersion, "TimeMgrVersion", kCensusSelVersion },
    { gestaltTSMTEVersion, "TSMTEVersion", kCensusSelVersion },
    { gestaltTSMTEAttr, "TSMTEAttr", kCensusSelAttr },
    { gestaltAVLTreeAttr, "AVLTreeAttr", kCensusSelAttr },
    { gestaltALMAttr, "ALMAttr", kCensusSelAttr },
    { gestaltTSMgrVersion, "TSMgrVersion", kCensusSelVersion },
    { gestaltTSMgrAttr, "TSMgrAttr", kCensusSelAttr },
    { gestaltSpeechAttr, "SpeechAttr", kCensusSelAttr },
    { gestaltTVAttr, "TVAttr", kCensusSelAttr },
    { gestaltATSUVersion, "ATSUVersion", kCensusSelVersion },
    { gestaltATSUFeatures, "ATSUFeatures", kCensusSelNum },
    { gestaltUSBAttr, "USBAttr", kCensusSelAttr },
    { gestaltUSBVersion, "USBVersion", kCensusSelVersion },
    { gestaltVersion, "Version", kCensusSelVersion },
    { gestaltVIA1Addr, "VIA1Addr", kCensusSelNum },
    { gestaltVIA2Addr, "VIA2Addr", kCensusSelNum },
    { gestaltVMAttr, "VMAttr", kCensusSelAttr },
    { gestaltVMInfoType, "VMInfoType", kCensusSelNum },
    { gestaltVMBackingStoreFileRefNum, "VMBackingStoreFileRefNum", kCensusSelNum },
    { gestaltALMVers, "ALMVers", kCensusSelNum },
    { gestaltWindowMgrAttr, "WindowMgrAttr", kCensusSelAttr },
    { gestaltTranslationAttr, "TranslationAttr", kCensusSelAttr },
    { gestaltExtToolboxTable, "ExtToolboxTable", kCensusSelAddr },
    { gestaltUSBPrinterSharingVersion, "USBPrinterSharingVersion", kCensusSelVersion },
    { gestaltWorldScriptIIVersion, "WorldScriptIIVersion", kCensusSelVersion },
    { gestaltWorldScriptIIAttr, "WorldScriptIIAttr", kCensusSelAttr },
};

#define kNowCensusSelectorCount \
    ((int)(sizeof kNowCensusSelectors / sizeof kNowCensusSelectors[0]))

/* Curated bit names for the attr selectors the census leans on; every
   other attr renders its set bits by number, honestly unrecognized. */
typedef struct {
    unsigned long selector;
    short bit;
    const char *name;
} NowCensusAttrBit;

static const NowCensusAttrBit kNowCensusAttrBits[] = {
    { gestaltHardwareAttr, 0, "VIA1" },
    { gestaltHardwareAttr, 1, "VIA2" },
    { gestaltHardwareAttr, 3, "ASC" },
    { gestaltHardwareAttr, 4, "SCC" },
    { gestaltHardwareAttr, 7, "SCSI" },
    { gestaltHardwareAttr, 19, "soft power off" },
    { gestaltHardwareAttr, 21, "SCSI 961" },
    { gestaltHardwareAttr, 22, "SCSI 962" },
    { gestaltHardwareAttr, 24, "universal ROM" },
    { gestaltHardwareAttr, 30, "enhanced LocalTalk" },
    { gestaltOSAttr, 0, "growable sys zone" },
    { gestaltOSAttr, 1, "launch can return" },
    { gestaltOSAttr, 2, "launch full FileSpec" },
    { gestaltOSAttr, 3, "launch control" },
    { gestaltOSAttr, 4, "temp mem support" },
    { gestaltOSAttr, 5, "real temp memory" },
    { gestaltOSAttr, 6, "temp mem tracked" },
    { gestaltOSAttr, 7, "IPC support" },
    { gestaltOSAttr, 8, "sys debugger support" },
    { gestaltOSAttr, 19, "native Process Mgr" },
    { gestaltFSAttr, 0, "full ext FS dispatching" },
    { gestaltFSAttr, 1, "FSSpec calls" },
    { gestaltFSAttr, 2, "File System Manager" },
    { gestaltFSAttr, 3, "FSM dynamic load" },
    { gestaltFSAttr, 4, "4 GB volumes" },
    { gestaltFSAttr, 5, "2 TB volumes" },
    { gestaltFSAttr, 6, "extended Disk Init" },
    { gestaltFSAttr, 7, "DT Mgr supports FSM" },
    { gestaltFSAttr, 8, "no MFS volumes" },
    { gestaltFSAttr, 9, "HFS Plus volumes" },
    { gestaltFSAttr, 12, "HFS Plus APIs" },
    { gestaltFSAttr, 13, "must use FCB accessors" },
    { gestaltPowerMgrAttr, 0, "Power Mgr exists" },
    { gestaltPowerMgrAttr, 1, "CPU idle" },
    { gestaltPowerMgrAttr, 2, "SCC power" },
    { gestaltPowerMgrAttr, 3, "sound power" },
    { gestaltPowerMgrAttr, 4, "dispatch exists" },
    { gestaltPowerMgrAttr, 5, "AV power state at sleep/wake" },
};

#define kNowCensusAttrBitCount \
    ((int)(sizeof kNowCensusAttrBits / sizeof kNowCensusAttrBits[0]))

#endif /* NOW_CENSUS_SELECTORS_H */
