#ifndef NOW_CONTINUITY_UDP_H
#define NOW_CONTINUITY_UDP_H

/* Continuity's lossy state lane. The bytes are always big-endian; these
   constants describe the wire and deliberately do not expose a packed C
   struct. The host is little-endian and the classic guest is big-endian,
   so sharing native layout here would only hide a protocol bug. */

#define NOW_CONTINUITY_VERSION 2u

#define NOW_CONTINUITY_STATE_MAGIC 0x4E574331UL /* NWC1 */
#define NOW_CONTINUITY_STATE_BYTES 40u

#define NOW_CONTINUITY_STATE_MAGIC_OFFSET 0u
#define NOW_CONTINUITY_STATE_VERSION_OFFSET 4u
#define NOW_CONTINUITY_STATE_FLAGS_OFFSET 6u
#define NOW_CONTINUITY_STATE_NONCE_HI_OFFSET 8u
#define NOW_CONTINUITY_STATE_NONCE_LO_OFFSET 12u
#define NOW_CONTINUITY_STATE_EPOCH_OFFSET 16u
#define NOW_CONTINUITY_STATE_POSITION_SEQ_OFFSET 20u
#define NOW_CONTINUITY_STATE_H_OFFSET 24u
#define NOW_CONTINUITY_STATE_V_OFFSET 26u
#define NOW_CONTINUITY_STATE_BUTTON_GENERATION_OFFSET 28u
#define NOW_CONTINUITY_STATE_REQUESTED_HZ_OFFSET 32u
#define NOW_CONTINUITY_STATE_RESERVED_OFFSET 34u
#define NOW_CONTINUITY_STATE_HOST_STAMP_OFFSET 36u

#define NOW_CONTINUITY_FLAG_INSIDE 0x0001u
/* Version 2 activates the button state and generation fields that version 1
   reserved. A transition is applied once, acknowledged by generation, and a
   held button is released by the resident even when the PPC app is starved. */
#define NOW_CONTINUITY_FLAG_PRIMARY_DOWN 0x0002u
#define NOW_CONTINUITY_FLAG_KEEPALIVE 0x0004u
#define NOW_CONTINUITY_KNOWN_FLAGS 0x0007u

#define NOW_CONTINUITY_ACK_MAGIC 0x4E574131UL /* NWA1 */
#define NOW_CONTINUITY_ACK_BYTES 44u

#define NOW_CONTINUITY_ACK_MAGIC_OFFSET 0u
#define NOW_CONTINUITY_ACK_VERSION_OFFSET 4u
#define NOW_CONTINUITY_ACK_STATE_OFFSET 6u
#define NOW_CONTINUITY_ACK_NONCE_HI_OFFSET 8u
#define NOW_CONTINUITY_ACK_NONCE_LO_OFFSET 12u
#define NOW_CONTINUITY_ACK_EPOCH_OFFSET 16u
#define NOW_CONTINUITY_ACK_POSITION_SEQ_OFFSET 20u
#define NOW_CONTINUITY_ACK_BUTTON_GENERATION_OFFSET 24u
#define NOW_CONTINUITY_ACK_ACCEPTED_HZ_OFFSET 28u
#define NOW_CONTINUITY_ACK_EXIT_REASON_OFFSET 30u
#define NOW_CONTINUITY_ACK_ARRIVAL_TICKS_OFFSET 32u
#define NOW_CONTINUITY_ACK_APPLY_TICKS_OFFSET 36u
#define NOW_CONTINUITY_ACK_REJECTED_PACKETS_OFFSET 40u

#define NOW_CONTINUITY_ACK_INACTIVE 0u
#define NOW_CONTINUITY_ACK_ARMED 1u
#define NOW_CONTINUITY_ACK_ACTIVE 2u

#define NOW_CONTINUITY_EXIT_NONE 0u
#define NOW_CONTINUITY_EXIT_HOST_LEFT 1u
#define NOW_CONTINUITY_EXIT_GUEST_INPUT 2u
#define NOW_CONTINUITY_EXIT_LEASE_EXPIRED 3u
#define NOW_CONTINUITY_EXIT_DISARMED 4u

#endif
