import SwiftUI

/// Platinum asset pack, ported from `attic/web/platinum.css` — which in turn
/// took its seven grays from the guest's hand-drawn kit (`ui_theme.c`).
/// Fonts are stand-ins; a ported Chicago/Geneva bitmap pack replaces them
/// later (mirror README, "Asset packs").
public enum Platinum {
    // The seven grays.
    public static let g0 = Color(hex: 0xFFFFFF)   // highlight
    public static let g1 = Color(hex: 0xEEEEEE)   // light face
    public static let g2 = Color(hex: 0xCCCCCC)   // face
    public static let g3 = Color(hex: 0xA6A6A6)   // mid
    public static let g4 = Color(hex: 0x888888)   // shadow
    public static let g5 = Color(hex: 0x555555)   // dark
    public static let g6 = Color(hex: 0x000000)   // frame

    /// OS 9 default blue desktop.
    public static let desktopBlue = Color(hex: 0x7395BD)

    /* The two accent colours below are MEASURED — read out of the guest's
       own `Apple platinum` theme file rather than chosen (see
       PlatinumAccentRamps.swift, generated by tools/extract-assets-offline).
       Both come from the ramp the shipped default theme names, Lavender.

       `selection` was ported as 0x333399 and the measurement agrees with
       it EXACTLY: it is Lavender's fifth step, unchanged here. The
       constant was right; all that has changed is that it can now be
       traced to the byte range it came from instead of to a CSS file. */

    /// The dark accent step. Menu-title fill and the derived-grid selection
    /// ring — a marker this side draws, not a fill the guest makes.
    public static let selection = Color(rgb: PlatinumAccent.active.steps[4])

    /// The colour a selected list row or run of text is filled with.
    ///
    /// The default scene writes this literally as its own RGBColor, and it
    /// is also Lavender's second step — two independent slots agreeing.
    /// It was previously `g2` (0xCCCCCC), which is a grey: right value for
    /// the *Gray Space* theme, one blue channel short for this one.
    public static let highlight = Color(rgb: PlatinumAccent.activeHighlight)

    // Logical surface (the guest screen); scenes carry rects in this space.
    public static let logicalSize = CGSize(width: 1024, height: 768)

    // Metrics (px in logical space).
    public static let menubarHeight: CGFloat = 20
    public static let titlebarHeight: CGFloat = 20
    public static let contentTop: CGFloat = 22

    // Chicago / Geneva stand-ins.
    public static func systemFont(_ size: CGFloat) -> Font {
        .custom("Charcoal", size: size)
        .weight(.medium)
    }
    public static func appFont(_ size: CGFloat) -> Font {
        .custom("Geneva", size: size)
    }
}

extension Color {
    /// Same arithmetic as `hex:`, named for what it carries: an extracted
    /// 0xRRGGBB out of a `clut`, not a literal somebody typed.
    init(rgb: UInt32) { self.init(hex: rgb) }

    init(hex: UInt32) {
        self.init(red: Double((hex >> 16) & 0xFF) / 255,
                  green: Double((hex >> 8) & 0xFF) / 255,
                  blue: Double(hex & 0xFF) / 255)
    }
}
