import SwiftUI
import MirrorKit

/// Platinum asset pack, ported from `attic/web/platinum.css` — which in turn
/// took its seven grays from the guest's hand-drawn kit (`ui_theme.c`).
/// Fonts are stand-ins; a ported Chicago/Geneva bitmap pack replaces them
/// later (mirror README, "Asset packs").
public enum Platinum {
    // The seven grays.
    public static let g0 = Color(hex: 0xFFFFFF)   // highlight
    public static let g1 = Color(hex: 0xEEEEEE)   // light face
    public static let g2 = Color(hex: 0xCCCCCC)   // face
    public static let g3 = Color(hex: 0xA6A6A6)   // mid
    public static let g4 = Color(hex: 0x888888)   // shadow
    public static let g5 = Color(hex: 0x555555)   // dark
    public static let g6 = Color(hex: 0x000000)   // frame

    /// OS 9 default blue desktop.
    public static let desktopBlue = Color(hex: 0x7395BD)

    /// The face a Dialog Manager window is erased with — the Appearance
    /// Manager's `kThemeBrushDialogBackgroundActive`.
    ///
    /// **MEASURED, NOT ASKED, and that distinction is the whole comment.**
    /// Counted out of the guest's own QMP screendump: the interior of the
    /// Date & Time control panel in
    /// `019-integration/date-and-time-guest.png` is 10149 of 11724 sampled
    /// pixels at (221,221,221), against 525 white. The renderer had been
    /// filling that face with `g0` — pure white — so every part of a panel
    /// the semantic pass did not draw over read as unfinished paper. One
    /// wrong constant, and it is most of why a panel pair looks unfinished.
    ///
    /// A MEASURED CONSTANT IS NOT AN ANSWER, it is a stand-in for one —
    /// and since 2026-08-07 the answer exists. `meta.theme.dialogBackground`
    /// carries what `GetThemeBrushAsColor(kThemeBrushDialogBackgroundActive,
    /// …)` returned on the guest at capture time, and `SceneTheme` prefers
    /// it. **This constant is now the FALLBACK ONLY**: a scene from a
    /// producer too old to ask, or a machine that refused the brush.
    ///
    /// It stays 0xDDDDDD because that is what was counted, and the value is
    /// confirmed by the machine — see docs/theme-colours.md for the ask
    /// beside the count.
    public static let dialogFace = Color(hex: 0xDDDDDD)

    /// Fallback for `meta.theme.alertBackground`
    /// (kThemeBrushAlertBackgroundActive).
    ///
    /// **It is a SEPARATE constant from `dialogFace` because it is a
    /// separate brush**, whatever the two happen to evaluate to under
    /// Platinum. Collapsing them would make the theme's ability to
    /// distinguish them unrepresentable here, which is the shape of every
    /// defect this field exists to end.
    public static let alertFace = Color(hex: 0xDDDDDD)

    /// Fallback for `meta.theme.documentBackground`
    /// (kThemeBrushDocumentWindowBackground). A document window's content
    /// really is white under Platinum; another theme may disagree, and now
    /// gets to.
    public static let documentFace = Color(hex: 0xFFFFFF)

    /* The two accent colours below are MEASURED — read out of the guest's
       own `Apple platinum` theme file rather than chosen (see
       PlatinumAccentRamps.swift, generated by tools/extract-assets-offline).
       Both come from the ramp the shipped default theme names, Lavender.

       `selection` was ported as 0x333399 and the measurement agrees with
       it EXACTLY: it is Lavender's fifth step, unchanged here. The
       constant was right; all that has changed is that it can now be
       traced to the byte range it came from instead of to a CSS file. */

    /// The dark accent step. Menu-title fill and the derived-grid selection
    /// ring — a marker this side draws, not a fill the guest makes.
    public static let selection = Color(rgb: PlatinumAccent.active.steps[4])

    /// The colour a selected list row or run of text is filled with, when
    /// the guest did not say. Fallback for `meta.theme.highlight`.
    ///
    /// **MEASURED 2026-08-07, AND IT OVERTURNED THE EXTRACTED ONE.**
    /// This was `PlatinumAccent.activeHighlight` (0xCCCCFF), read offline
    /// out of the theme file's default scene and corroborated by two slots
    /// in that file agreeing. The running machine disagrees with both:
    ///
    /// * `LMGetHiliteRGB` on a stock Mac OS 9.1 guest answers **0x97A1DE**
    ///   (`meta.theme.highlight`, guest build `beda718861c0`, screen depth
    ///   32).
    /// * The guest's own screendump agrees exactly — the selected sidebar
    ///   row is 0x97A1DE across 2399 of 3240 sampled pixels (the rest is
    ///   the row's text and icon).
    ///
    /// So 0xCCCCFF had **never been seen on a screen**: `AccentRampTests`
    /// says in its own words that no capture in the corpus carried a
    /// selected row, and forcing the constant to magenta changed no pixel
    /// anywhere. It is a true fact about a FILE and was the wrong answer to
    /// "what does this machine fill a selection with". `PlatinumAccent`
    /// keeps it, correctly labelled, because the file does say that.
    ///
    /// WHAT IS STILL UNKNOWN: one machine, once. The live value is the
    /// user's Appearance highlight setting, so another install may hold
    /// something else — which is exactly why the answer belongs on the
    /// wire and this constant is only what stands in when nobody asked.
    /// See docs/theme-colours.md.
    public static let highlightFallbackRGB: UInt32 = 0x97A1DE
    public static let highlight = Color(rgb: Platinum.highlightFallbackRGB)

    // Logical surface (the guest screen); scenes carry rects in this space.
    public static let logicalSize = CGSize(width: 1024, height: 768)

    // Metrics (px in logical space).
    public static let menubarHeight: CGFloat = 20
    public static let titlebarHeight = CGFloat(WindowChrome.titlebarHeight)
    /// A TITLED window's drawn content top, and it is two pixels below
    /// where the guest puts it (`WindowChrome.contentOrigin`) — the
    /// bevel and hairline under the title bar. Measured 2026-08-07: NOW's
    /// own "Take Screenshot" button, content-local (172, 423) in a window
    /// at (28, 50), is drawn on the guest at (200, 493) = rect + (0, 20).
    /// Two pixels down and one right is small enough that no click has
    /// ever missed because of it, so it is named rather than changed —
    /// moving it churns every tuned render probe. The DIALOG case of the
    /// same drift was fourteen pixels and is fixed; see
    /// `WindowChrome.contentOrigin`.
    public static let contentTop: CGFloat = 22

    // Chicago / Geneva stand-ins.
    public static func systemFont(_ size: CGFloat) -> Font {
        .custom("Charcoal", size: size)
        .weight(.medium)
    }
    public static func appFont(_ size: CGFloat) -> Font {
        .custom("Geneva", size: size)
    }
}

extension Color {
    /// Same arithmetic as `hex:`, named for what it carries: an extracted
    /// 0xRRGGBB out of a `clut`, not a literal somebody typed.
    init(rgb: UInt32) { self.init(hex: rgb) }

    init(hex: UInt32) {
        self.init(red: Double((hex >> 16) & 0xFF) / 255,
                  green: Double((hex >> 8) & 0xFF) / 255,
                  blue: Double(hex & 0xFF) / 255)
    }
}
