// GENERATED by tools/extract-assets-offline --- do not edit by hand.
//
// The Appearance theme's named accent ramps, read as NUMBERS out of
// `System Folder/Appearance/Theme Files/Apple platinum` on a guest disk image.
// The theme file carries no chrome bitmaps (docs/asset-extraction-
// offline.md); these `clut` resources are the half of it that IS
// liftable, and they are specification rather than art: the exact
// eight-step tables the Appearance Manager tints with.
//
// Source image: now-mirror-stage.qcow2
// Extracted:    2026-08-06
// Ramps:        21 `clut` resources, 876024 B fork
//
// Apple's colour tables. Private repo only, as the bitmaps are.

import Foundation

/// One named accent ramp: eight steps, light to dark, ending in black.
public struct AccentRamp: Sendable, Equatable {
    public let name: String
    /// Resource id of the `clut` this came from, so a value can be
    /// traced back to the byte range it was read out of.
    public let clutID: Int
    /// 0xRRGGBB, light to dark. Empty for `Black & White`, which is a
    /// real ramp with no entries rather than a missing one.
    public let steps: [UInt32]

    public var isEmpty: Bool { steps.isEmpty }
}

public enum PlatinumAccent {
    public static let sourceFile = "System Folder/Appearance/Theme Files/Apple platinum"
    public static let sourceImage = "now-mirror-stage.qcow2"
    public static let extracted = "2026-08-06"

    public static let azul = AccentRamp(
        name: "Azul", clutID: 200,
        steps: [0xAFC9FF, 0x93B6EA, 0x7599D0, 0x6686B7, 0x4A6999, 0x30467D, 0x293C6A, 0x000000])
    public static let bondi = AccentRamp(
        name: "Bondi", clutID: 201,
        steps: [0xC8F8E9, 0x67DACD, 0x5AB9AD, 0x308F91, 0x0D716A, 0x00454B, 0x003333, 0x000000])
    public static let copper = AccentRamp(
        name: "Copper", clutID: 202,
        steps: [0xFFFFCC, 0xFFCC99, 0xFF9966, 0xCC6633, 0x993300, 0x660000, 0x220000, 0x000000])
    public static let crimson = AccentRamp(
        name: "Crimson", clutID: 203,
        steps: [0xFFCCCC, 0xFF9999, 0xFF6666, 0xCC3333, 0x990000, 0x770000, 0x440000, 0x000000])
    public static let emerald = AccentRamp(
        name: "Emerald", clutID: 204,
        steps: [0xCCFFCC, 0x66FF99, 0x33CC66, 0x339966, 0x006633, 0x004400, 0x002200, 0x000000])
    public static let frenchBlue = AccentRamp(
        name: "French Blue", clutID: 205,
        steps: [0xCCCCFF, 0xB0B0EA, 0x8585BC, 0x666699, 0x51517C, 0x333366, 0x26264D, 0x000000])
    public static let gold = AccentRamp(
        name: "Gold", clutID: 206,
        steps: [0xFFFF99, 0xFFFF00, 0xCCCC00, 0x999900, 0x666600, 0x333300, 0x111111, 0x000000])
    public static let ivy = AccentRamp(
        name: "Ivy", clutID: 207,
        steps: [0xCCFFCC, 0x99CC99, 0x669966, 0x336633, 0x003300, 0x002200, 0x001100, 0x000000])
    public static let lavender = AccentRamp(
        name: "Lavender", clutID: 208,
        steps: [0xEEEEEE, 0xCCCCFF, 0x9999FF, 0x6666CC, 0x333399, 0x000088, 0x000055, 0x000000])
    public static let pistachio = AccentRamp(
        name: "Pistachio", clutID: 209,
        steps: [0xEDFFB7, 0xDBFD75, 0xCDED6D, 0xB5E040, 0x99CC3E, 0x669900, 0x336600, 0x000000])
    public static let magenta = AccentRamp(
        name: "Magenta", clutID: 210,
        steps: [0xFFCCFF, 0xFF99FF, 0xCC66CC, 0x993399, 0x660066, 0x330033, 0x220000, 0x000000])
    public static let nutmeg = AccentRamp(
        name: "Nutmeg", clutID: 211,
        steps: [0xFED9B3, 0xECB277, 0xCC9966, 0x996633, 0x663300, 0x451F18, 0x220000, 0x000000])
    public static let poppy = AccentRamp(
        name: "Poppy", clutID: 212,
        steps: [0xFFC05C, 0xFE9C02, 0xFE8502, 0xF46F19, 0xFE4200, 0xE14200, 0xA43000, 0x000000])
    public static let plum = AccentRamp(
        name: "Plum", clutID: 213,
        steps: [0xFFCCFF, 0xDEA4DE, 0xBE80BE, 0x996699, 0x663366, 0x4A0A4A, 0x330033, 0x000000])
    public static let rose = AccentRamp(
        name: "Rose", clutID: 214,
        steps: [0xFFDCDC, 0xEFC8C8, 0xCC9999, 0x996666, 0x794242, 0x541F1F, 0x350000, 0x000000])
    public static let sapphire = AccentRamp(
        name: "Sapphire", clutID: 215,
        steps: [0xEEEEEE, 0x99CCFF, 0x6699FF, 0x3366FF, 0x0033CC, 0x000099, 0x000055, 0x000000])
    public static let silver = AccentRamp(
        name: "Silver", clutID: 216,
        steps: [0xEEEEEE, 0xCCCCCC, 0xAAAAAA, 0x777777, 0x555555, 0x333333, 0x222222, 0x000000])
    public static let teal = AccentRamp(
        name: "Teal", clutID: 217,
        steps: [0xB9EEEE, 0x99CCCC, 0x669999, 0x477979, 0x336666, 0x074C4C, 0x003333, 0x000000])
    public static let turquoise = AccentRamp(
        name: "Turquoise", clutID: 218,
        steps: [0xCCFFFF, 0x66FFFF, 0x00CCFF, 0x0099CC, 0x006699, 0x003366, 0x000022, 0x000000])
    public static let sunny = AccentRamp(
        name: "Sunny", clutID: 219,
        steps: [0xFFFEE6, 0xFEF491, 0xF5DB61, 0xE6C144, 0xCCAB3B, 0xAA8F35, 0x887126, 0x000000])
    public static let blackAndWhite = AccentRamp(
        name: "Black & White", clutID: 220,
        steps: [])

    public static let all: [AccentRamp] = [
        azul,
        bondi,
        copper,
        crimson,
        emerald,
        frenchBlue,
        gold,
        ivy,
        lavender,
        pistachio,
        magenta,
        nutmeg,
        poppy,
        plum,
        rose,
        sapphire,
        silver,
        teal,
        turquoise,
        sunny,
        blackAndWhite,
    ]

    public static func named(_ name: String) -> AccentRamp? {
        all.first { $0.name == name }
    }

    /// The ramp in force.
    ///
    /// Read offline, from the `Mac OS Default` scene (`scen`
    /// 2000) in the theme file itself — the shipped default,
    /// which names its accent in one slot and its highlight colour in
    /// another ("Purple", RGB 0xCCCCFF). Those two agree: the highlight is this
    /// ramp's second step, exactly.
    ///
    /// shipped default, never overridden on this image.
    ///
    /// THE SEAM: this is what the theme file SAYS, not what a running
    /// AppearanceLib answers. `GetThemeAccentColors` on the guest is the
    /// only thing that can close that gap, and it is plan 016 P2's query
    /// applet. When it lands, this constant is what it replaces.
    public static let active = lavender

    /// The highlight colour the default scene writes literally, as its
    /// own RGBColor rather than as a ramp index. Text and list-row
    /// selection are filled with THIS.
    public static let activeHighlight: UInt32 = 0xCCCCFF
}
