#!/usr/bin/env python3
"""Stamp a build identity into a binary, and beside it.

    gen_build_id.py <out.c> <out.buildid> <symbol> <source> [source...]

WHY THIS EXISTS, and it is the most-repeated failure on this bench: a
guest booted with a STALE extension looks exactly like a guest with a
live one. The file is in the Extensions folder, the Gestalt selector
answers, the table has a magic number - and the code running is
yesterday's. Agents lose hours to it.

So the identity is not a version number anyone maintains: it is a hash
of the sources that produced this binary, compiled INTO it, and written
to a sidecar file at the same moment. The host reads the sidecar next to
the .bin it staged and demands the guest report the same number back
before any measurement is believed. One source of truth, no agreement
between two hashing schemes required, and a rebuild the host forgot to
stage fails loudly instead of quietly reporting the old build's numbers.
"""

import hashlib
import os
import sys


def main():
    if len(sys.argv) < 5:
        raise SystemExit(__doc__)
    out_c, out_id, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    digest = hashlib.sha256()
    for path in sorted(sys.argv[4:]):
        with open(path, "rb") as fh:
            digest.update(os.path.basename(path).encode())
            digest.update(fh.read())
    build_id = int.from_bytes(digest.digest()[:4], "big")

    text = (
        "/* Generated by tools/gen_build_id.py - do not edit, do not\n"
        "   commit. The value is a hash of the sources that produced this\n"
        "   binary; the host demands it back off the guest before it\n"
        "   believes a measurement. */\n"
        '#include "cursor_rig.h"\n\n'
        f"const RigU32 {symbol} = 0x{build_id:08X}U;\n")
    # Only rewrite on change, so an unchanged build does not relink and
    # invalidate a staged image for no reason.
    if not (os.path.exists(out_c) and open(out_c).read() == text):
        with open(out_c, "w") as fh:
            fh.write(text)
    with open(out_id, "w") as fh:
        fh.write(f"{build_id:08X}\n")


if __name__ == "__main__":
    main()
