# buildstamp.cmake — deterministic identity for the complete PPC build surface.
#
# The identity is SHA-256 over stable repository-relative paths, each file's
# SHA-256, and the compiler/toolchain profile. It deliberately excludes clocks
# and checkout paths: identical inputs under the same toolchain reproduce the
# same build ID, while parallel branches can share a release version without
# sharing an identity.

file(GLOB_RECURSE _stamp_sources
     "${ROOT}/now-guest-ppc/src/*.c"
     "${ROOT}/now-guest-ppc/src/*.h"
     "${ROOT}/now-guest-ppc/src/*.r"
     "${ROOT}/now-guest-ppc/src/*.S"
     "${ROOT}/now-guest-ppc/resources/*"
     "${ROOT}/contract/*.h")
list(APPEND _stamp_sources
     "${ROOT}/now-guest-ppc/CMakeLists.txt"
     "${ROOT}/now-guest-ppc/cmake/buildstamp.cmake"
     "${ROOT}/now-guest-ppc/tools/name_macbinary.py"
     "${ROOT}/now-guest-shared/src/console_history.c"
     "${ROOT}/now-guest-shared/src/console_history.h"
     "${ROOT}/now-guest-shared/src/now_semantic_guard.c"
     "${ROOT}/now-guest-shared/src/now_semantic_guard.h"
     "${ROOT}/now-guest-shared/src/now_act_guard.c"
     "${ROOT}/now-guest-shared/src/now_act_guard.h"
     "${ROOT}/now-guest-shared/src/now_act_inflight.c"
     "${ROOT}/now-guest-shared/src/now_act_inflight.h")
list(REMOVE_DUPLICATES _stamp_sources)
list(SORT _stamp_sources)

set(_stamp_accum "schema=now-component-build-v2\ncomponent=application\n")
string(APPEND _stamp_accum "toolchain=${TOOLCHAIN_ID}\n")
foreach(_file IN LISTS _stamp_sources)
    if(IS_DIRECTORY "${_file}")
        continue()
    endif()
    file(RELATIVE_PATH _path "${ROOT}" "${_file}")
    file(SHA256 "${_file}" _hash)
    string(APPEND _stamp_accum "${_path}\t${_hash}\n")
endforeach()
string(SHA256 _stamp_hash "${_stamp_accum}")

set(_stamp_body
"/* GENERATED by cmake/buildstamp.cmake — do not edit, do not commit. */
#ifndef NOW_BUILDSTAMP_H
#define NOW_BUILDSTAMP_H

#define NOW_BUILD_ID \"${_stamp_hash}\"
/* Compatibility name for the live-test tools which read this define. */
#define NOW_SRC_HASH \"${_stamp_hash}\"

#endif /* NOW_BUILDSTAMP_H */
")

set(_stamp_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _stamp_old)
endif()
if(NOT _stamp_old STREQUAL _stamp_body)
    file(WRITE "${OUT}" "${_stamp_body}")
    message(STATUS "application build identity: ${_stamp_hash}")
endif()
