# Generated by tools/now-api-contract. Do not edit.
_now_complete() {
  local cur="${COMP_WORDS[COMP_CWORD]}" prev="${COMP_WORDS[COMP_CWORD-1]}"
  local domains="guests connections console files transfers events api" generic_operations="catalog.search diagnostics.capture diagnostics.framebuffer diagnostics.transfer files.capabilities files.get files.list files.mutate files.reveal files.stat guests.capabilities guests.census guests.facts guests.list interface.control.act interface.menu.act interface.observe interface.text.get interface.text.set interface.window.act logs.guest.tail logs.host.tail mirror.act mirror.find mirror.journal mirror.lifecycle mirror.metrics mirror.snapshot mirror.start mirror.status mirror.wait mirror.waitForSettlement processes.activate processes.list processes.quit screen.capture screen.stream software.launch software.list transfers.cancel"
  local domain="" verb="" domain_index=-1 candidates="" i
  for ((i=1; i<COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      guests|connections|console|files|transfers|events|api)
        if [[ -z $domain ]]; then domain="${COMP_WORDS[i]}"; domain_index=$i
        elif [[ -z $verb ]]; then verb="${COMP_WORDS[i]}"
        fi ;;
      *) if [[ $domain_index -ge 0 && -z $verb && $i -eq $((domain_index+1)) ]]; then verb="${COMP_WORDS[i]}"; fi ;;
    esac
  done
  if [[ -z $domain ]]; then
    COMPREPLY=( $(compgen -W "$domains --endpoint --api-key --json --guest" -- "$cur") )
    return
  fi
  if [[ $COMP_CWORD -eq $((domain_index+1)) ]]; then
    case "$domain" in
    guests) candidates="list status use" ;;
    connections) candidates="list start stop disconnect" ;;
    console) candidates="" ;;
    files) candidates="list stat mkdir move trash restore get put" ;;
    transfers) candidates="list status cancel" ;;
    events) candidates="watch" ;;
    api) candidates="operations call" ;;
    esac
    COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
    return
  fi
  if [[ $domain == api && $verb == call && $COMP_CWORD -eq $((domain_index+2)) ]]; then
    COMPREPLY=( $(compgen -W "$generic_operations" -- "$cur") )
    return
  fi
  if [[ $domain == files && $verb == put && $prev == --container ]]; then
    COMPREPLY=( $(compgen -W "data macbinary" -- "$cur") )
  fi
}
complete -F _now_complete now
