# Generated by tools/now-api-contract. Do not edit.
_now_complete() {
  local commands="guests connections console files transfers events api"
  if [[ $COMP_CWORD -eq 1 ]]; then COMPREPLY=( $(compgen -W "$commands" -- "${COMP_WORDS[1]}") ); fi
}
complete -F _now_complete now
