// Generated by tools/product-features from product/features.yaml; do not edit.

import Foundation

enum ProductFeatureID: String, CaseIterable, Sendable {
    case classicPowerPC = "classic.powerpc"
    case residentExtension = "resident.extension"
    case classicPreCarbon = "classic.pre-carbon"
}

enum ProductFeatureReleaseState: String, Sendable {
    case included
    case optional
    case excluded
}

enum ProductFeatureRuntimeBinding: Equatable, Sendable {
    case intrinsic
    case capabilityNegotiated
    case flag(key: String, defaultEnabled: Bool)
}

struct ProductFeatureDefinition: Equatable, Sendable {
    let id: ProductFeatureID
    let title: String
    let releaseState: ProductFeatureReleaseState
    let releaseNote: String
    let runtimeBinding: ProductFeatureRuntimeBinding
}

enum GeneratedProductFeatures {
    static let activeProfileID = "alpha"
    static let definitions: [ProductFeatureDefinition] = [
        ProductFeatureDefinition(
            id: .classicPowerPC,
            title: "PowerPC Carbon guest",
            releaseState: .included,
            releaseNote: "Primary classic guest and the supported alpha path.",
            runtimeBinding: .intrinsic),
        ProductFeatureDefinition(
            id: .residentExtension,
            title: "NOW Extension",
            releaseState: .optional,
            releaseNote: "Bundled with the alpha; install it only for the resident-backed features listed below.",
            runtimeBinding: .capabilityNegotiated),
        ProductFeatureDefinition(
            id: .classicPreCarbon,
            title: "Pre-Carbon support (NOW-68K)",
            releaseState: .excluded,
            releaseNote: "The current NOW-68K build is stale and excluded from the alpha.",
            runtimeBinding: .flag(key: "classic.pre-carbon", defaultEnabled: false)),
    ]

    static let byID = Dictionary(uniqueKeysWithValues:
        definitions.map { ($0.id, $0) })
}
