/*
 * census_selectors.h - the documented Gestalt selector table the census
 * walks, plus the attr-bit names and a meaning note for each selector.
 * The selector/bit inventory was snapshotted mechanically from Universal
 * Interfaces 3.4 Gestalt.h (Technology: Mac OS 9.1) - the same header
 * this application compiles against, so a selector or bit that leaves
 * the interfaces fails the build instead of drifting. Labels are the
 * Apple symbol names minus the gestalt/Has prefix. The meaning notes are
 * this project's own words (rewritten 2026-08-24 so no Apple header
 * prose ships in the tree), and they carry only what the symbol name and
 * kind column do not already say - most rows need none.
 *
 * Gestalt has no enumeration API: this table IS the walk, and the report
 * says so. The row inventory is generated - do not add or remove rows by
 * hand; see the generator in the census slice's history. The meaning
 * notes are hand-maintained.
 */
#ifndef NOW_CENSUS_SELECTORS_H
#define NOW_CENSUS_SELECTORS_H

#include <Carbon.h>
#include "census_decode.h"

static const NowCensusSelector kNowCensusSelectors[] = {
    { gestaltAddressingModeAttr, "AddressingModeAttr", kCensusSelAttr, "" },
    { gestaltAFPClient, "AFPClient", kCensusSelNum, "" },
    { gestaltAliasMgrAttr, "AliasMgrAttr", kCensusSelAttr, "" },
    { gestaltAppearanceAttr, "AppearanceAttr", kCensusSelAttr, "" },
    { gestaltAppearanceVersion, "AppearanceVersion", kCensusSelVersion, "" },
    { gestaltArbitorAttr, "ArbitorAttr", kCensusSelAttr, "" },
    { gestaltAppleScriptVersion, "AppleScriptVersion", kCensusSelVersion, "" },
    { gestaltAppleScriptAttr, "AppleScriptAttr", kCensusSelAttr, "" },
    { gestaltATAAttr, "ATAAttr", kCensusSelAttr, "" },
    { gestaltATalkVersion, "ATalkVersion", kCensusSelVersion, "detailed form of the AppleTalk version" },
    { gestaltAppleTalkVersion, "AppleTalkVersion", kCensusSelVersion, "" },
    { gestaltAUXVersion, "AUXVersion", kCensusSelVersion, "meaningful only when A/UX is installed" },
    { gestaltMacOSCompatibilityBoxAttr, "MacOSCompatibilityBoxAttr", kCensusSelAttr, "" },
    { gestaltBusClkSpeed, "BusClkSpeed", kCensusSelHz, "main I/O bus clock" },
    { gestaltCloseViewAttr, "CloseViewAttr", kCensusSelAttr, "" },
    { gestaltCarbonVersion, "CarbonVersion", kCensusSelVersion, "" },
    { gestaltCFMAttr, "CFMAttr", kCensusSelAttr, "" },
    { gestaltCollectionMgrVersion, "CollectionMgrVersion", kCensusSelVersion, "" },
    { gestaltColorMatchingAttr, "ColorMatchingAttr", kCensusSelAttr, "" },
    { gestaltColorMatchingVersion, "ColorMatchingVersion", kCensusSelVersion, "" },
    { gestaltControlMgrVersion, "ControlMgrVersion", kCensusSelVersion, "first reported as 3.0.1, on early Mac OS X" },
    { gestaltControlMgrAttr, "ControlMgrAttr", kCensusSelAttr, "" },
    { gestaltConnMgrAttr, "ConnMgrAttr", kCensusSelAttr, "" },
    { gestaltColorPickerVersion, "ColorPickerVersion", kCensusSelVersion, "" },
    { gestaltComponentMgr, "ComponentMgr", kCensusSelNum, "" },
    { gestaltComponentPlatform, "ComponentPlatform", kCensusSelNum, "component platform id" },
    { gestaltNativeCPUtype, "NativeCPUtype", kCensusSelNum, "" },
    { gestaltNativeCPUfamily, "NativeCPUfamily", kCensusSelNum, "" },
    { gestaltCRMAttr, "CRMAttr", kCensusSelAttr, "" },
    { gestaltControlStripVersion, "ControlStripVersion", kCensusSelVersion, "selector formerly spelled 'sdvr'" },
    { gestaltCTBVersion, "CTBVersion", kCensusSelVersion, "Communications Toolbox" },
    { gestaltDBAccessMgrAttr, "DBAccessMgrAttr", kCensusSelAttr, "" },
    { gestaltDiskCacheSize, "DiskCacheSize", kCensusSelSize, "disk cache buffer total" },
    { gestaltSDPFindVersion, "SDPFindVersion", kCensusSelVersion, "OCE Standard Directory Panel component" },
    { gestaltDictionaryMgrAttr, "DictionaryMgrAttr", kCensusSelAttr, "" },
    { gestaltDITLExtAttr, "DITLExtAttr", kCensusSelAttr, "" },
    { gestaltDialogMgrAttr, "DialogMgrAttr", kCensusSelAttr, "" },
    { gestaltDesktopPicturesAttr, "DesktopPicturesAttr", kCensusSelAttr, "" },
    { gestaltDisplayMgrVers, "DisplayMgrVers", kCensusSelNum, "" },
    { gestaltDisplayMgrAttr, "DisplayMgrAttr", kCensusSelAttr, "" },
    { gestaltDragMgrAttr, "DragMgrAttr", kCensusSelAttr, "" },
    { gestaltDrawSprocketVersion, "DrawSprocketVersion", kCensusSelVersion, "NumVersion form" },
    { gestaltDigitalSignatureVersion, "DigitalSignatureVersion", kCensusSelVersion, "version carried in the low word" },
    { gestaltDTPFeatures, "DTPFeatures", kCensusSelNum, "" },
    { gestaltDTPInfo, "DTPInfo", kCensusSelNum, "response is a GestaltDTPInfoHdle handle" },
    { gestaltEasyAccessAttr, "EasyAccessAttr", kCensusSelAttr, "" },
    { gestaltEditionMgrAttr, "EditionMgrAttr", kCensusSelAttr, "" },
    { gestaltAppleEventsAttr, "AppleEventsAttr", kCensusSelAttr, "" },
    { gestaltExtensionTableVersion, "ExtensionTableVersion", kCensusSelVersion, "" },
    { gestaltFBCIndexingState, "FBCIndexingState", kCensusSelNum, "" },
    { gestaltFBCVersion, "FBCVersion", kCensusSelVersion, "" },
    { gestaltFileMappingAttr, "FileMappingAttr", kCensusSelAttr, "" },
    { gestaltFloppyAttr, "FloppyAttr", kCensusSelAttr, "" },
    { gestaltFinderAttr, "FinderAttr", kCensusSelAttr, "" },
    { gestaltFindFolderAttr, "FindFolderAttr", kCensusSelAttr, "" },
    { gestaltFindFolderRedirectionAttr, "FindFolderRedirectionAttr", kCensusSelAttr, "" },
    { gestaltFontMgrAttr, "FontMgrAttr", kCensusSelAttr, "" },
    { gestaltFPUType, "FPUType", kCensusSelNum, "" },
    { gestaltFSAttr, "FSAttr", kCensusSelAttr, "" },
    { gestaltAdminFeaturesFlagsAttr, "AdminFeaturesFlagsAttr", kCensusSelAttr, "" },
    { gestaltFSMVersion, "FSMVersion", kCensusSelVersion, "File System Manager, for external file systems" },
    { gestaltFXfrMgrAttr, "FXfrMgrAttr", kCensusSelAttr, "" },
    { gestaltGraphicsAttr, "GraphicsAttr", kCensusSelAttr, "" },
    { gestaltGraphicsVersion, "GraphicsVersion", kCensusSelVersion, "" },
    { gestaltHardwareAttr, "HardwareAttr", kCensusSelAttr, "" },
    { gestaltHelpMgrAttr, "HelpMgrAttr", kCensusSelAttr, "" },
    { gestaltHardwareVendorCode, "HardwareVendorCode", kCensusSelNum, "" },
    { gestaltCompressionMgr, "CompressionMgr", kCensusSelNum, "Image Compression Manager" },
    { gestaltIconUtilitiesAttr, "IconUtilitiesAttr", kCensusSelAttr, "" },
    { gestaltInternalDisplay, "InternalDisplay", kCensusSelNum, "slot holding the internal display" },
    { gestaltKeyboardType, "KeyboardType", kCensusSelNum, "" },
    { gestaltUDFSupport, "UDFSupport", kCensusSelNum, "cross-implementation UDF signalling" },
    { gestaltLowMemorySize, "LowMemorySize", kCensusSelSize, "low-memory global area" },
    { gestaltLogicalRAMSize, "LogicalRAMSize", kCensusSelSize, "" },
    { gestaltMachineType, "MachineType", kCensusSelNum, "" },
    { gestaltSMPMailerVersion, "SMPMailerVersion", kCensusSelVersion, "OCE StandardMail component" },
    { gestaltMediaBay, "MediaBay", kCensusSelNum, "" },
    { gestaltMessageMgrVersion, "MessageMgrVersion", kCensusSelVersion, "QuickDraw GX printing Message Manager" },
    { gestaltMenuMgrAttr, "MenuMgrAttr", kCensusSelAttr, "" },
    { gestaltMultipleUsersState, "MultipleUsersState", kCensusSelNum, "response is a MultiUserGestaltHandle; see Folders.h" },
    { gestaltMachineIcon, "MachineIcon", kCensusSelNum, "icon id for this machine model" },
    { gestaltMiscAttr, "MiscAttr", kCensusSelAttr, "" },
    { gestaltMixedModeVersion, "MixedModeVersion", kCensusSelVersion, "" },
    { gestaltQuickTimeConferencing, "QuickTimeConferencing", kCensusSelNum, "" },
    { gestaltMemoryMapAttr, "MemoryMapAttr", kCensusSelAttr, "" },
    { gestaltMMUType, "MMUType", kCensusSelNum, "" },
    { gestaltUserVisibleMachineName, "UserVisibleMachineName", kCensusSelNum, "response is a StringPtr to the model's display name" },
    { gestaltMPCallableAPIsAttr, "MPCallableAPIsAttr", kCensusSelAttr, "" },
    { gestaltStdNBPAttr, "StdNBPAttr", kCensusSelAttr, "" },
    { gestaltNotificationMgrAttr, "NotificationMgrAttr", kCensusSelAttr, "" },
    { gestaltNameRegistryVersion, "NameRegistryVersion", kCensusSelVersion, "NameRegistryLib; meaningful from System 7.5.2" },
    { gestaltNuBusSlotCount, "NuBusSlotCount", kCensusSelCount, "logical NuBus slots" },
    { gestaltOCEToolboxVersion, "OCEToolboxVersion", kCensusSelVersion, "" },
    { gestaltOCEToolboxAttr, "OCEToolboxAttr", kCensusSelAttr, "" },
    { gestaltOpenFirmwareInfo, "OpenFirmwareInfo", kCensusSelNum, "" },
    { gestaltOSAttr, "OSAttr", kCensusSelAttr, "" },
    { gestaltOSTable, "OSTable", kCensusSelAddr, "OS trap table" },
    { gestaltOpenTptNetworkSetup, "OpenTptNetworkSetup", kCensusSelNum, "" },
    { gestaltOpenTptNetworkSetupVersion, "OpenTptNetworkSetupVersion", kCensusSelVersion, "" },
    { gestaltOpenTptRemoteAccess, "OpenTptRemoteAccess", kCensusSelNum, "" },
    { gestaltOpenTptRemoteAccessVersion, "OpenTptRemoteAccessVersion", kCensusSelVersion, "" },
    { gestaltOpenTptVersions, "OpenTptVersions", kCensusSelVersion, "NumVersion; present from Open Transport 1.1" },
    { gestaltOpenTpt, "OpenTpt", kCensusSelNum, "" },
    { gestaltPCCard, "PCCard", kCensusSelNum, "" },
    { gestaltProcClkSpeed, "ProcClkSpeed", kCensusSelHz, "processor clock" },
    { gestaltPCXAttr, "PCXAttr", kCensusSelAttr, "" },
    { gestaltLogicalPageSize, "LogicalPageSize", kCensusSelSize, "" },
    { gestaltScreenCaptureMain, "ScreenCaptureMain", kCensusSelNum, "" },
    { gestaltScreenCaptureDir, "ScreenCaptureDir", kCensusSelNum, "directory id where screen captures land" },
    { gestaltGXPrintingMgrVersion, "GXPrintingMgrVersion", kCensusSelVersion, "QuickDraw GX Printing Manager" },
    { gestaltPopupAttr, "PopupAttr", kCensusSelAttr, "" },
    { gestaltPowerMgrAttr, "PowerMgrAttr", kCensusSelAttr, "" },
    { gestaltPowerMgrVers, "PowerMgrVers", kCensusSelNum, "" },
    { gestaltPPCToolboxAttr, "PPCToolboxAttr", kCensusSelAttr, "" },
    { gestaltPowerPCProcessorFeatures, "PowerPCProcessorFeatures", kCensusSelNum, "" },
    { gestaltProcessorType, "ProcessorType", kCensusSelNum, "" },
    { gestaltSDPPromptVersion, "SDPPromptVersion", kCensusSelVersion, "OCE Standard Directory Panel component" },
    { gestaltParityAttr, "ParityAttr", kCensusSelAttr, "" },
    { gestaltQD3DVersion, "QD3DVersion", kCensusSelVersion, "packed BCD" },
    { gestaltQD3DViewer, "QD3DViewer", kCensusSelNum, "" },
    { gestaltQuickdrawVersion, "QuickdrawVersion", kCensusSelVersion, "" },
    { gestaltQD3D, "QD3D", kCensusSelNum, "" },
    { gestaltGXVersion, "GXVersion", kCensusSelVersion, "QuickDraw GX overall" },
    { gestaltQuickdrawFeatures, "QuickdrawFeatures", kCensusSelNum, "" },
    { gestaltQDTextVersion, "QDTextVersion", kCensusSelVersion, "" },
    { gestaltQDTextFeatures, "QDTextFeatures", kCensusSelNum, "" },
    { gestaltQuickTimeConferencingInfo, "QuickTimeConferencingInfo", kCensusSelNum, "pointer to conferencing info" },
    { gestaltQuickTimeVersion, "QuickTimeVersion", kCensusSelVersion, "" },
    { gestaltQuickTimeFeatures, "QuickTimeFeatures", kCensusSelNum, "" },
    { gestaltQuickTimeStreamingFeatures, "QuickTimeStreamingFeatures", kCensusSelNum, "" },
    { gestaltQuickTimeStreamingVersion, "QuickTimeStreamingVersion", kCensusSelVersion, "" },
    { gestaltQTVRMgrAttr, "QTVRMgrAttr", kCensusSelAttr, "" },
    { gestaltQTVRMgrVers, "QTVRMgrVers", kCensusSelNum, "" },
    { gestaltPhysicalRAMSize, "PhysicalRAMSize", kCensusSelSize, "" },
    { gestaltRBVAddr, "RBVAddr", kCensusSelNum, "RBV chip base" },
    { gestaltROMSize, "ROMSize", kCensusSelSize, "" },
    { gestaltROMVersion, "ROMVersion", kCensusSelVersion, "" },
    { gestaltResourceMgrAttr, "ResourceMgrAttr", kCensusSelAttr, "" },
    { gestaltResourceMgrBugFixesAttrs, "ResourceMgrBugFixesAttrs", kCensusSelNum, "" },
    { gestaltRealtimeMgrAttr, "RealtimeMgrAttr", kCensusSelAttr, "" },
    { gestaltSafeOFAttr, "SafeOFAttr", kCensusSelAttr, "" },
    { gestaltSCCReadAddr, "SCCReadAddr", kCensusSelNum, "SCC read base" },
    { gestaltSCCWriteAddr, "SCCWriteAddr", kCensusSelNum, "SCC write base" },
    { gestaltScrapMgrAttr, "ScrapMgrAttr", kCensusSelAttr, "" },
    { gestaltScriptMgrVersion, "ScriptMgrVersion", kCensusSelVersion, "" },
    { gestaltScriptCount, "ScriptCount", kCensusSelCount, "active script systems" },
    { gestaltSCSI, "SCSI", kCensusSelNum, "" },
    { gestaltControlStripAttr, "ControlStripAttr", kCensusSelAttr, "" },
    { gestaltSDPStandardDirectoryVersion, "SDPStandardDirectoryVersion", kCensusSelVersion, "OCE Standard Directory Panel component" },
    { gestaltSerialAttr, "SerialAttr", kCensusSelAttr, "" },
    { gestaltShutdownAttributes, "ShutdownAttributes", kCensusSelNum, "" },
    { gestaltNuBusConnectors, "NuBusConnectors", kCensusSelNum, "NuBus connector bitmap" },
    { gestaltSlotAttr, "SlotAttr", kCensusSelAttr, "" },
    { gestaltFirstSlotNumber, "FirstSlotNumber", kCensusSelNum, "first physical slot number" },
    { gestaltSoundAttr, "SoundAttr", kCensusSelAttr, "" },
    { gestaltSplitOSAttr, "SplitOSAttr", kCensusSelAttr, "" },
    { gestaltSMPSPSendLetterVersion, "SMPSPSendLetterVersion", kCensusSelVersion, "OCE StandardMail component" },
    { gestaltSpeechRecognitionAttr, "SpeechRecognitionAttr", kCensusSelAttr, "" },
    { gestaltSpeechRecognitionVersion, "SpeechRecognitionVersion", kCensusSelVersion, "full API support begins at 0x0150" },
    { gestaltSoftwareVendorCode, "SoftwareVendorCode", kCensusSelNum, "" },
    { gestaltSoftwareVendorLicensee, "SoftwareVendorLicensee", kCensusSelNum, "licensee-sold system software" },
    { gestaltStandardFileAttr, "StandardFileAttr", kCensusSelAttr, "" },
    { gestaltSysArchitecture, "SysArchitecture", kCensusSelNum, "" },
    { gestaltSystemUpdateVersion, "SystemUpdateVersion", kCensusSelVersion, "" },
    { gestaltSystemVersion, "SystemVersion", kCensusSelVersion, "" },
    { gestaltToolboxTable, "ToolboxTable", kCensusSelAddr, "Toolbox trap table" },
    { gestaltTextEditVersion, "TextEditVersion", kCensusSelVersion, "" },
    { gestaltTEAttr, "TEAttr", kCensusSelAttr, "" },
    { gestaltTeleMgrAttr, "TeleMgrAttr", kCensusSelAttr, "" },
    { gestaltTermMgrAttr, "TermMgrAttr", kCensusSelAttr, "" },
    { gestaltThreadMgrAttr, "ThreadMgrAttr", kCensusSelAttr, "" },
    { gestaltTimeMgrVersion, "TimeMgrVersion", kCensusSelVersion, "" },
    { gestaltTSMTEVersion, "TSMTEVersion", kCensusSelVersion, "" },
    { gestaltTSMTEAttr, "TSMTEAttr", kCensusSelAttr, "" },
    { gestaltAVLTreeAttr, "AVLTreeAttr", kCensusSelAttr, "" },
    { gestaltALMAttr, "ALMAttr", kCensusSelAttr, "" },
    { gestaltTSMgrVersion, "TSMgrVersion", kCensusSelVersion, "" },
    { gestaltTSMgrAttr, "TSMgrAttr", kCensusSelAttr, "" },
    { gestaltSpeechAttr, "SpeechAttr", kCensusSelAttr, "" },
    { gestaltTVAttr, "TVAttr", kCensusSelAttr, "" },
    { gestaltATSUVersion, "ATSUVersion", kCensusSelVersion, "" },
    { gestaltATSUFeatures, "ATSUFeatures", kCensusSelNum, "" },
    { gestaltUSBAttr, "USBAttr", kCensusSelAttr, "" },
    { gestaltUSBVersion, "USBVersion", kCensusSelVersion, "" },
    { gestaltVersion, "Version", kCensusSelVersion, "" },
    { gestaltVIA1Addr, "VIA1Addr", kCensusSelNum, "VIA 1 chip base" },
    { gestaltVIA2Addr, "VIA2Addr", kCensusSelNum, "VIA 2 chip base" },
    { gestaltVMAttr, "VMAttr", kCensusSelAttr, "" },
    { gestaltVMInfoType, "VMInfoType", kCensusSelNum, "" },
    { gestaltVMBackingStoreFileRefNum, "VMBackingStoreFileRefNum", kCensusSelNum, "VM backing-store file refNum, low word" },
    { gestaltALMVers, "ALMVers", kCensusSelNum, "Settings Manager; companion of ALMAttr" },
    { gestaltWindowMgrAttr, "WindowMgrAttr", kCensusSelAttr, "" },
    { gestaltTranslationAttr, "TranslationAttr", kCensusSelAttr, "" },
    { gestaltExtToolboxTable, "ExtToolboxTable", kCensusSelAddr, "extended Toolbox trap table" },
    { gestaltUSBPrinterSharingVersion, "USBPrinterSharingVersion", kCensusSelVersion, "" },
    { gestaltWorldScriptIIVersion, "WorldScriptIIVersion", kCensusSelVersion, "" },
    { gestaltWorldScriptIIAttr, "WorldScriptIIAttr", kCensusSelAttr, "" },
};

#define kNowCensusSelectorCount \
    ((int)(sizeof kNowCensusSelectors / sizeof kNowCensusSelectors[0]))

static const NowCensusAttrBit kNowCensusAttrBits[] = {
    { gestaltAddressingModeAttr, 0, "32Bit Addressing" },
    { gestaltAddressingModeAttr, 1, "32Bit Sys Zone" },
    { gestaltAddressingModeAttr, 2, "32Bit Capable" },
    { gestaltAliasMgrAttr, 0, "Alias Mgr Present" },
    { gestaltAliasMgrAttr, 1, "Alias Mgr Supports Remote Appletalk" },
    { gestaltAliasMgrAttr, 2, "Alias Mgr Supports AOCE Keychain" },
    { gestaltAliasMgrAttr, 3, "Alias Mgr Resolve Alias File With Mount Options" },
    { gestaltAliasMgrAttr, 4, "Alias Mgr Follows Aliases When Resolving" },
    { gestaltAliasMgrAttr, 5, "Alias Mgr Supports Extended Calls" },
    { gestaltAliasMgrAttr, 6, "Alias Mgr Supports FS Calls" },
    { gestaltAppearanceAttr, 0, "Appearance Exists" },
    { gestaltAppearanceAttr, 1, "Appearance Compat Mode" },
    { gestaltArbitorAttr, 0, "Serial Arbitration Exists" },
    { gestaltAppleScriptAttr, 0, "Apple Script Present" },
    { gestaltAppleScriptAttr, 1, "Apple Script Power PC Support" },
    { gestaltATAAttr, 0, "ATA Present" },
    { gestaltMacOSCompatibilityBoxAttr, 0, "Mac OS Compatibility Box Present" },
    { gestaltMacOSCompatibilityBoxAttr, 1, "Mac OS Compatibility Box Has Serial" },
    { gestaltMacOSCompatibilityBoxAttr, 2, "Mac OS Compatibility Boxless" },
    { gestaltCloseViewAttr, 0, "Close View Enabled" },
    { gestaltCloseViewAttr, 1, "Close View Display Mgr Friendly" },
    { gestaltCFMAttr, 0, "CFM Present" },
    { gestaltCFMAttr, 2, "CFM99Present" },
    { gestaltColorMatchingAttr, 0, "High Level Matching" },
    { gestaltColorMatchingAttr, 1, "Color Matching Lib Loaded" },
    { gestaltControlMgrAttr, 0, "Control Mgr Present Bit" },
    { gestaltConnMgrAttr, 0, "Conn Mgr Present" },
    { gestaltConnMgrAttr, 1, "Conn Mgr CM Search Fix" },
    { gestaltConnMgrAttr, 2, "Conn Mgr Error String" },
    { gestaltConnMgrAttr, 3, "Conn Mgr Multi Async IO" },
    { gestaltCRMAttr, 0, "CRM Present" },
    { gestaltCRMAttr, 1, "CRM Persistent Fix" },
    { gestaltCRMAttr, 2, "CRM Tool Rsrc Calls" },
    { gestaltDBAccessMgrAttr, 0, "DB Access Mgr Present" },
    { gestaltDictionaryMgrAttr, 0, "Dictionary Mgr Present" },
    { gestaltDITLExtAttr, 0, "DITL Ext Present" },
    { gestaltDITLExtAttr, 1, "DITL Ext Supports Ictb" },
    { gestaltDialogMgrAttr, 0, "Dialog Mgr Present Bit" },
    { gestaltDesktopPicturesAttr, 0, "Desktop Pictures Installed" },
    { gestaltDesktopPicturesAttr, 1, "Desktop Pictures Displayed" },
    { gestaltDisplayMgrAttr, 0, "Display Mgr Present" },
    { gestaltDisplayMgrAttr, 2, "Display Mgr Can Switch Mirrored" },
    { gestaltDisplayMgrAttr, 3, "Display Mgr Set Depth Notifies" },
    { gestaltDisplayMgrAttr, 4, "Display Mgr Can Confirm" },
    { gestaltDisplayMgrAttr, 5, "Display Mgr Color Sync Aware" },
    { gestaltDisplayMgrAttr, 6, "Display Mgr Generates Profiles" },
    { gestaltDragMgrAttr, 0, "Drag Mgr Present" },
    { gestaltDragMgrAttr, 1, "Drag Mgr Floating Wind" },
    { gestaltDragMgrAttr, 2, "PPC Drag Lib Present" },
    { gestaltDragMgrAttr, 3, "Drag Mgr Has Image Support" },
    { gestaltDragMgrAttr, 4, "Can Start Drag In Float Window" },
    { gestaltDragMgrAttr, 5, "Set Drag Image Updates" },
    { gestaltEasyAccessAttr, 0, "Easy Access Off" },
    { gestaltEasyAccessAttr, 1, "Easy Access On" },
    { gestaltEasyAccessAttr, 2, "Easy Access Sticky" },
    { gestaltEasyAccessAttr, 3, "Easy Access Locked" },
    { gestaltEditionMgrAttr, 0, "Edition Mgr Present" },
    { gestaltEditionMgrAttr, 1, "Edition Mgr Translation Aware" },
    { gestaltAppleEventsAttr, 0, "Apple Events Present" },
    { gestaltAppleEventsAttr, 1, "Scripting Support" },
    { gestaltAppleEventsAttr, 2, "OSL In System" },
    { gestaltFileMappingAttr, 0, "File Mapping Present" },
    { gestaltFileMappingAttr, 1, "File Mapping Multiple Files Fix" },
    { gestaltFloppyAttr, 0, "Floppy Is MFM Only" },
    { gestaltFloppyAttr, 1, "Floppy Is Manual Eject" },
    { gestaltFloppyAttr, 2, "Floppy Uses Disk In Place" },
    { gestaltFinderAttr, 0, "Finder Drop Event" },
    { gestaltFinderAttr, 1, "Finder Magic Placement" },
    { gestaltFinderAttr, 2, "Finder Calls AE Process" },
    { gestaltFinderAttr, 3, "OSL Compliant Finder" },
    { gestaltFinderAttr, 4, "Finder Supports4GB Volumes" },
    { gestaltFinderAttr, 6, "Finder Has Clippings" },
    { gestaltFinderAttr, 7, "Finder Full Drag Manager Support" },
    { gestaltFinderAttr, 8, "Finder Floppy Root Comments" },
    { gestaltFinderAttr, 9, "Finder Large And Not Saved Flavors OK" },
    { gestaltFinderAttr, 10, "Finder Uses Extensible Folder Manager" },
    { gestaltFinderAttr, 11, "Finder Understands Redirected Desktop Folder" },
    { gestaltFindFolderAttr, 0, "Find Folder Present" },
    { gestaltFindFolderAttr, 1, "Folder Desc Support" },
    { gestaltFindFolderAttr, 2, "Folder Mgr Follows Aliases When Resolving" },
    { gestaltFindFolderAttr, 3, "Folder Mgr Supports Extended Calls" },
    { gestaltFindFolderAttr, 4, "Folder Mgr Supports Domains" },
    { gestaltFindFolderAttr, 5, "Folder Mgr Supports FS Calls" },
    { gestaltFontMgrAttr, 0, "Outline Fonts" },
    { gestaltFSAttr, 0, "Full Ext FS Dispatching" },
    { gestaltFSAttr, 1, "FS Spec Calls" },
    { gestaltFSAttr, 2, "File System Manager" },
    { gestaltFSAttr, 3, "FSM Does Dynamic Load" },
    { gestaltFSAttr, 4, "FS Supports4GB Vols" },
    { gestaltFSAttr, 5, "FS Supports2TB Vols" },
    { gestaltFSAttr, 6, "Extended Disk Init" },
    { gestaltFSAttr, 7, "DT Mgr Supports FSM" },
    { gestaltFSAttr, 8, "FS No MFS Vols" },
    { gestaltFSAttr, 9, "FS Supports HFS Plus Vols" },
    { gestaltFSAttr, 10, "FS Incompatible DFA82" },
    { gestaltAdminFeaturesFlagsAttr, 0, "Finder Uses Special Open Folders File" },
    { gestaltFXfrMgrAttr, 0, "F Xfr Mgr Present" },
    { gestaltFXfrMgrAttr, 1, "F Xfr Mgr Multi File" },
    { gestaltFXfrMgrAttr, 2, "F Xfr Mgr Error String" },
    { gestaltFXfrMgrAttr, 3, "F Xfr Mgr Async" },
    { gestaltHardwareAttr, 0, "VIA1" },
    { gestaltHardwareAttr, 1, "VIA2" },
    { gestaltHardwareAttr, 3, "ASC" },
    { gestaltHardwareAttr, 4, "SCC" },
    { gestaltHardwareAttr, 7, "SCSI" },
    { gestaltHardwareAttr, 19, "Soft Power Off" },
    { gestaltHardwareAttr, 21, "SCSI961" },
    { gestaltHardwareAttr, 22, "SCSI962" },
    { gestaltHardwareAttr, 24, "Universal ROM" },
    { gestaltHardwareAttr, 30, "Enhanced Ltalk" },
    { gestaltHelpMgrAttr, 0, "Help Mgr Present" },
    { gestaltHelpMgrAttr, 1, "Help Mgr Extensions" },
    { gestaltHelpMgrAttr, 30, "Apple Guide Is Debug" },
    { gestaltHelpMgrAttr, 31, "Apple Guide Present" },
    { gestaltIconUtilitiesAttr, 0, "Icon Utilities Present" },
    { gestaltIconUtilitiesAttr, 1, "Icon Utilities Has48Pixel Icons" },
    { gestaltIconUtilitiesAttr, 2, "Icon Utilities Has32Bit Icons" },
    { gestaltIconUtilitiesAttr, 3, "Icon Utilities Has8Bit Deep Masks" },
    { gestaltIconUtilitiesAttr, 4, "Icon Utilities Has Icon Services" },
    { gestaltMenuMgrAttr, 0, "Menu Mgr Present Bit" },
    { gestaltMenuMgrAttr, 1, "Menu Mgr Aqua Layout Bit" },
    { gestaltMenuMgrAttr, 2, "Menu Mgr Multiple Items With Command ID Bit" },
    { gestaltMenuMgrAttr, 3, "Menu Mgr Retains Icon Ref Bit" },
    { gestaltMenuMgrAttr, 4, "Menu Mgr Sends Menu Bounds To Def Proc Bit" },
    { gestaltMiscAttr, 0, "Scrolling Throttle" },
    { gestaltMiscAttr, 2, "Square Menu Bar" },
    { gestaltMemoryMapAttr, 0, "Memory Map Sparse" },
    { gestaltMPCallableAPIsAttr, 0, "MP File Manager" },
    { gestaltMPCallableAPIsAttr, 1, "MP Device Manager" },
    { gestaltMPCallableAPIsAttr, 2, "MP Trap Calls" },
    { gestaltStdNBPAttr, 0, "Std NBP Present" },
    { gestaltStdNBPAttr, 1, "Std NBP Supports Auto Position" },
    { gestaltNotificationMgrAttr, 0, "Notification Present" },
    { gestaltOSAttr, 0, "Sys Zone Growable" },
    { gestaltOSAttr, 1, "Launch Can Return" },
    { gestaltOSAttr, 2, "Launch Full File Spec" },
    { gestaltOSAttr, 3, "Launch Control" },
    { gestaltOSAttr, 4, "Temp Mem Support" },
    { gestaltOSAttr, 5, "Real Temp Memory" },
    { gestaltOSAttr, 6, "Temp Mem Tracked" },
    { gestaltOSAttr, 7, "IPC Support" },
    { gestaltOSAttr, 8, "Sys Debugger Support" },
    { gestaltOSAttr, 19, "Native Process Mgr Bit" },
    { gestaltPCXAttr, 0, "PCX Has8and16Bit FAT" },
    { gestaltPCXAttr, 1, "PCX Has Pro DOS" },
    { gestaltPCXAttr, 2, "PCX New UI" },
    { gestaltPCXAttr, 3, "PCX Use IC Mapping" },
    { gestaltPopupAttr, 0, "Popup Present" },
    { gestaltPowerMgrAttr, 0, "P Mgr Exists" },
    { gestaltPowerMgrAttr, 1, "P Mgr CPU Idle" },
    { gestaltPowerMgrAttr, 2, "P Mgr SCC" },
    { gestaltPowerMgrAttr, 3, "P Mgr Sound" },
    { gestaltPowerMgrAttr, 4, "P Mgr Dispatch Exists" },
    { gestaltPowerMgrAttr, 5, "P Mgr Supports AV Power State At Sleep Wake" },
    { gestaltParityAttr, 0, "Parity Capability" },
    { gestaltParityAttr, 1, "Parity Enabled" },
    { gestaltQTVRMgrAttr, 0, "QTVR Mgr Present" },
    { gestaltQTVRMgrAttr, 1, "QTVR Obj Movies Present" },
    { gestaltQTVRMgrAttr, 2, "QTVR Cylinder Panos Present" },
    { gestaltQTVRMgrAttr, 3, "QTVR Cubic Panos Present" },
    { gestaltResourceMgrAttr, 0, "Partial Rsrcs" },
    { gestaltResourceMgrAttr, 1, "Resource Overrides" },
    { gestaltRealtimeMgrAttr, 0, "Realtime Mgr Present" },
    { gestaltSafeOFAttr, 0, "VM Zeros Pages Bit" },
    { gestaltSafeOFAttr, 1, "Init Heap Zeros Out Heaps Bit" },
    { gestaltSafeOFAttr, 2, "New Handle Returns Zeroed Memory Bit" },
    { gestaltSafeOFAttr, 3, "New Ptr Returns Zeroed Memory Bit" },
    { gestaltSafeOFAttr, 4, "File Allocation Zeroed Blocks Bit" },
    { gestaltScrapMgrAttr, 0, "Scrap Mgr Translation Aware" },
    { gestaltControlStripAttr, 0, "Control Strip Exists" },
    { gestaltControlStripAttr, 1, "Control Strip Version Fixed" },
    { gestaltControlStripAttr, 2, "Control Strip User Font" },
    { gestaltControlStripAttr, 3, "Control Strip User Hot Key" },
    { gestaltSerialAttr, 0, "GP Ia To DC Da" },
    { gestaltSerialAttr, 1, "GP Ia To R Tx Ca" },
    { gestaltSerialAttr, 2, "GP Ib To DC Db" },
    { gestaltSerialAttr, 3, "Hide Port A" },
    { gestaltSerialAttr, 4, "Hide Port B" },
    { gestaltSerialAttr, 5, "Port A Disabled" },
    { gestaltSerialAttr, 6, "Port B Disabled" },
    { gestaltSlotAttr, 0, "Slot Mgr Exists" },
    { gestaltSlotAttr, 1, "Nu Bus Present" },
    { gestaltSlotAttr, 2, "SE Slot Present" },
    { gestaltSlotAttr, 3, "SE30Slot Present" },
    { gestaltSlotAttr, 4, "Portable Slot Present" },
    { gestaltSoundAttr, 0, "Stereo Capability" },
    { gestaltSoundAttr, 1, "Stereo Mixing" },
    { gestaltSoundAttr, 3, "Sound IO Mgr Present" },
    { gestaltSoundAttr, 4, "Built In Sound Input" },
    { gestaltSoundAttr, 5, "Sound Input Device" },
    { gestaltSoundAttr, 6, "Play And Record" },
    { gestaltSoundAttr, 7, "16Bit Sound IO" },
    { gestaltSoundAttr, 8, "Stereo Input" },
    { gestaltSoundAttr, 9, "Line Level Input" },
    { gestaltSoundAttr, 10, "Snd Play Double Buffer" },
    { gestaltSoundAttr, 11, "Multi Channels" },
    { gestaltSoundAttr, 12, "16Bit Audio Support" },
    { gestaltSplitOSAttr, 0, "Split OS Boot Drive Is Network Volume" },
    { gestaltSplitOSAttr, 1, "Split OS Aware" },
    { gestaltSplitOSAttr, 2, "Split OS Enabler Volume Is Different From Boot Volume" },
    { gestaltSplitOSAttr, 3, "Split OS Machine Name Set To Network Name Temp" },
    { gestaltSplitOSAttr, 5, "Split OS Machine Name Startup Disk Is Non Persistent" },
    { gestaltSpeechRecognitionAttr, 1, "Desktop Speech Recognition" },
    { gestaltSpeechRecognitionAttr, 2, "Telephone Speech Recognition" },
    { gestaltStandardFileAttr, 0, "Standard File58" },
    { gestaltStandardFileAttr, 1, "Standard File Translation Aware" },
    { gestaltStandardFileAttr, 2, "Standard File Has Color Icons" },
    { gestaltStandardFileAttr, 3, "Standard File Use Generic Icons" },
    { gestaltStandardFileAttr, 4, "Standard File Has Dynamic Volume Allocation" },
    { gestaltTEAttr, 0, "TE Has Get Hilite Rgn" },
    { gestaltTEAttr, 1, "TE Supports Inline Input" },
    { gestaltTEAttr, 2, "TE Supports Text Objects" },
    { gestaltTEAttr, 3, "TE Has White Background" },
    { gestaltTeleMgrAttr, 0, "Tele Mgr Present" },
    { gestaltTeleMgrAttr, 1, "Tele Mgr Power PC Support" },
    { gestaltTeleMgrAttr, 2, "Tele Mgr Sound Streams" },
    { gestaltTeleMgrAttr, 3, "Tele Mgr Auto Answer" },
    { gestaltTeleMgrAttr, 4, "Tele Mgr Ind Handset" },
    { gestaltTeleMgrAttr, 5, "Tele Mgr Silence Detect" },
    { gestaltTeleMgrAttr, 6, "Tele Mgr New TEL New Support" },
    { gestaltTermMgrAttr, 0, "Term Mgr Present" },
    { gestaltTermMgrAttr, 2, "Term Mgr Error String" },
    { gestaltThreadMgrAttr, 0, "Thread Mgr Present" },
    { gestaltThreadMgrAttr, 1, "Specific Match Support" },
    { gestaltThreadMgrAttr, 2, "Threads Library Present" },
    { gestaltTSMTEAttr, 0, "TSMTE Present" },
    { gestaltTSMTEAttr, 0, "TSMTE" },
    { gestaltAVLTreeAttr, 0, "AVL Tree Present Bit" },
    { gestaltALMAttr, 0, "ALM Present" },
    { gestaltALMAttr, 1, "ALM Has SF Group" },
    { gestaltALMAttr, 2, "ALM Has CFM Support" },
    { gestaltALMAttr, 3, "ALM Has Rescan Notifiers" },
    { gestaltTSMgrAttr, 0, "TSM Display Mgr Aware Bit" },
    { gestaltTSMgrAttr, 1, "TS Mdoes TSMTE Bit" },
    { gestaltSpeechAttr, 0, "Speech Mgr Present" },
    { gestaltSpeechAttr, 1, "Speech Has PPC Glue" },
    { gestaltTVAttr, 0, "TV Tuner" },
    { gestaltTVAttr, 1, "Sound Fader" },
    { gestaltTVAttr, 2, "HW Closed Captioning" },
    { gestaltTVAttr, 3, "IR Remote" },
    { gestaltTVAttr, 4, "Vid Decoder Scaler" },
    { gestaltTVAttr, 5, "Stereo Decoder" },
    { gestaltTVAttr, 6, "Serial Fader" },
    { gestaltTVAttr, 7, "FM Tuner" },
    { gestaltTVAttr, 8, "System IR Function" },
    { gestaltTVAttr, 9, "IR Disabled" },
    { gestaltTVAttr, 10, "I Need IR Power Off Confirm" },
    { gestaltTVAttr, 11, "Zoomed Video" },
    { gestaltUSBAttr, 0, "USB Present" },
    { gestaltUSBAttr, 1, "USB Has Isoch" },
    { gestaltVMAttr, 0, "VM Present" },
    { gestaltVMAttr, 1, "VM Has Lock Memory For Output" },
    { gestaltVMAttr, 3, "VM Filemapping On" },
    { gestaltVMAttr, 4, "VM Has Paging Control" },
    { gestaltWindowMgrAttr, 0, "Window Mgr Present Bit" },
    { gestaltWindowMgrAttr, 1, "Extended Window Attributes" },
    { gestaltWindowMgrAttr, 1, "Extended Window Attributes Bit" },
    { gestaltWindowMgrAttr, 2, "Floating Windows" },
    { gestaltWindowMgrAttr, 2, "Floating Windows Bit" },
    { gestaltWindowMgrAttr, 3, "Window Buffering" },
    { gestaltWindowMgrAttr, 3, "Window Buffering Bit" },
    { gestaltWindowMgrAttr, 4, "Window Live Resize Bit" },
    { gestaltWindowMgrAttr, 5, "Window Minimize To Dock Bit" },
    { gestaltWindowMgrAttr, 6, "Window Shadows Bit" },
    { gestaltWindowMgrAttr, 7, "Sheets Are Window Modal Bit" },
    { gestaltTranslationAttr, 0, "Translation Mgr Exists" },
    { gestaltTranslationAttr, 1, "Translation Mgr Hint Order" },
    { gestaltTranslationAttr, 2, "Translation PPC Avail" },
    { gestaltTranslationAttr, 3, "Translation Get Path API Avail" },
    { gestaltWorldScriptIIAttr, 0, "WSII Can Print Without Pr General Bit" },
};

#define kNowCensusAttrBitCount \
    ((int)(sizeof kNowCensusAttrBits / sizeof kNowCensusAttrBits[0]))

#endif /* NOW_CENSUS_SELECTORS_H */
