#include "build_stamp.h"
#include "build_stamp_gen.h"

/* Return the build stamp: a 12-hex-char hash over all source files, and
   the build time. The hash is the true identity (it changes iff the sources
   changed); the timestamp is for human reading only.

   Generated by cmake/buildstamp.cmake on every build. See that file for
   why content hashing replaces clock-based stamping. */
const char *now_build_stamp(void)
{
    /* Return "{HASH} {ISO8601Z}" — e.g. "a1b2c3d4e5f6 2026-08-01T12:34:56Z" */
    return NOW_SRC_HASH " " NOW_BUILT_AT;
}
