/* Generated by tools/product-features from product/features.yaml; do not edit. */
#ifndef NOW_PRODUCT_FEATURES_GENERATED_H
#define NOW_PRODUCT_FEATURES_GENERATED_H

typedef enum {
    kNowProductFeatureClassicPowerPC = 0,
    kNowProductFeatureResidentExtension = 1,
    kNowProductFeatureClassicPreCarbon = 2,
    kNowProductFeatureCount
} NowProductFeatureID;

typedef enum {
    kNowFeatureReleaseIncluded = 1,
    kNowFeatureReleaseOptional = 2,
    kNowFeatureReleaseExcluded = 3
} NowFeatureReleaseState;

typedef enum {
    kNowFeatureRuntimeIntrinsic = 1,
    kNowFeatureRuntimeCapability = 2,
    kNowFeatureRuntimeFlag = 3
} NowFeatureRuntimeBinding;

typedef struct {
    NowProductFeatureID id;
    const char *stable_id;
    NowFeatureReleaseState release_state;
    const char *release_note;
    NowFeatureRuntimeBinding runtime_binding;
    const char *flag_key;
    int runtime_default;
} NowProductFeatureDefinition;

extern const char kNowProductFeatureActiveProfile[];
extern const NowProductFeatureDefinition kNowProductFeatures[kNowProductFeatureCount];
const NowProductFeatureDefinition *now_product_feature_find(NowProductFeatureID id);

#endif /* NOW_PRODUCT_FEATURES_GENERATED_H */
