/* Generated by tools/product-features from product/features.yaml; do not edit. */
#include "product_features.generated.h"

const char kNowProductFeatureActiveProfile[] = "alpha";

const NowProductFeatureDefinition kNowProductFeatures[kNowProductFeatureCount] = {
    { kNowProductFeatureClassicPowerPC, "classic.powerpc", kNowFeatureReleaseIncluded, "Primary classic guest and the supported alpha path.", kNowFeatureRuntimeIntrinsic, 0, 0 },
    { kNowProductFeatureResidentExtension, "resident.extension", kNowFeatureReleaseOptional, "Bundled with the alpha; install it only for the resident-backed features listed below.", kNowFeatureRuntimeCapability, 0, 0 },
    { kNowProductFeatureClassicPreCarbon, "classic.pre-carbon", kNowFeatureReleaseExcluded, "The current NOW-68K build is stale and excluded from the alpha.", kNowFeatureRuntimeFlag, "classic.pre-carbon", 0 },
};

const NowProductFeatureDefinition *now_product_feature_find(NowProductFeatureID id)
{
    if ((int)id < 0 || id >= kNowProductFeatureCount) {
        return 0;
    }
    return &kNowProductFeatures[(int)id];
}
