#ifndef NOW_PRODUCT_IDENTITY_H
#define NOW_PRODUCT_IDENTITY_H

/* Product name: "New Old World", "NOW" for short (decided 2026-07-19). */
#define PRODUCT_DISPLAY_NAME "New Old World"
#define PRODUCT_WINDOW_TITLE "New Old World"
#define PRODUCT_CREATOR_CODE 'NOWo'
#include "product_version.h"

#define PRODUCT_VERSION_MAJOR NOW_PRODUCT_VERSION_MAJOR
#define PRODUCT_VERSION_MINOR NOW_PRODUCT_VERSION_MINOR
#define PRODUCT_VERSION_PATCH NOW_PRODUCT_VERSION_PATCH
#define PRODUCT_VERSION NOW_PRODUCT_VERSION

#endif
